resources-icons-Sim
initReplayImage
	"Tools.UIMaskEditor new openOnClass: self andSelector: #initReplayImage"
	
	<resource: #image>
	^Image
		extent: 27 @ 25
		depth: 8
		bitsPerPixel: 8
		palette:
			(MappedPalette
				withColors:
					(#(#(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(6841 6809 6874)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(5653 5075 6488)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(6070 6070 6070)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(7163 6874 7484)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(4882 4143 5878)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(4850 3950 6103)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(6360 5846 7002)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(5267 4818 5814)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(6681 6327 7195)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(5524 4689 6681)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(5589 5107 6199)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(5910 5267 6713)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(7387 7163 7644)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(4818 3983 5781)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(6584 6167 7130)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(5492 4753 6327)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(4689 3886 5685)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(5814 5107 6649)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(5814 5364 6392)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(6167 5685 6713)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(6135 5621 6809)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(7291 7034 7548)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(5300 4464 6488)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(5814 5332 6424)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(7130 6874 7548)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(6038 5460 6745)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(4914 4111 5910)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(7516 7355 7677)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(5203 4336 6392)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(5942 5685 6295)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(5910 5300 6713)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(7420 7163 7644)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(5974 5974 5974)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(6584 6231 7098)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(8062 8062 8094)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(5460 4657 6488)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(5492 5075 6038)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(6970 6970 6970)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(5814 5139 6649)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(7291 7034 7580)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(6167 5781 6649)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(5043 4721 5524)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(6841 6617 7130)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(7195 6906 7484)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(4914 3950 6103)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(7516 7323 7741)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(6713 6327 7227)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(5621 4882 6456)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(8191 8191 8191)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(5942 5300 6713)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(7420 7163 7677)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(6649 6649 6649)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(4753 3886 5685)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(4721 3918 5685)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(6103 5396 7130)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(5010 4143 6167)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(6809 6488 7323)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(5749 5524 6038)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(6006 5235 7066)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(6103 5492 6713)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(7548 7323 7741)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(6777 6681 6841)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(7098 7098 7098)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(4818 4047 5814)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(5492 4753 6424)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(5492 4721 6456)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(6649 6617 6713)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(4721 3918 5717)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(5846 5300 6520)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(5878 5428 6360)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(6552 6552 6552)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(5396 4561 6392)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(5396 4593 6360)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(6841 6488 7323)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(6006 5267 7066)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(6070 5460 6809)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(5235 4368 6424)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(5300 4753 5974)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(6713 6360 7259)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(5621 5010 6392)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(6777 6649 6906)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(6006 5814 6199)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(4882 4047 5781)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(4882 4368 5460)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(6327 5878 6809)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(5235 5107 5364)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(6327 6263 6424)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(5524 4753 6424)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(5524 4786 6392)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(7002 7002 7002)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(5846 5267 6584)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(4753 3918 5717)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(4753 4047 5589)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(6199 5685 6809)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(6231 6135 6327)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(6552 6552 6584)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(6874 6488 7323)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(5685 4882 6809)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(7227 7098 7355)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(6070 5749 6552)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(7548 7355 7773)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(6424 6038 6906)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(7901 7805 7966)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(6809 6713 6841)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(4818 3918 6006)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(6295 5974 6777)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(4753 3918 5749)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(4721 3886 5814)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(4721 3854 5846)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(6199 5621 6906)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(7677 7516 7837)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(6231 6038 6456)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(7677 7677 7677)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(5364 4529 6520)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(6552 6295 6874)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(5910 5910 5910)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(6103 5524 6777)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(7130 7130 7130)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(5653 4914 6520)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(5235 4561 5974)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(7773 7677 7934)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(7002 6681 7387)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(4721 3886 5846)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(6199 5653 6906)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(6584 6584 6584)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(5075 4304 6070)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(6552 6231 6970)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(8030 7966 8062)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(6874 6584 7291)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(5396 4529 6520)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(5460 5396 5589)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(7259 7195 7291)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(4657 3822 5653)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(5717 4914 6809)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(6874 6520 7355)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(6135 5846 6456)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(7901 7837 7998)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(5300 4753 6070)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(7901 7805 8030)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(5621 4786 6713)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(6038 6038 6038)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(6327 5814 6970)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(7805 7677 7934)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(8126 8126 8158)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(7034 7002 7066)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(7002 6681 7420)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(7034 7034 7034)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(5043 4143 6295)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(5814 5460 6199)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(5781 5075 6617)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(4657 3854 5653)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(6103 5557 6809)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(6135 5653 6681)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(6456 6038 6970)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(6456 5974 7034)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(6135 6135 6199)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(4882 3918 6038)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(4914 4464 5460)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(6327 5814 7002)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(5589 5332 5910)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(5910 5653 6263)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(5878 5267 6681)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(4786 3983 5749)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(4818 4143 5557)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(5075 4143 6295)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(6231 5910 6681)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(5396 4561 6552)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(8030 7998 8094)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(5781 5107 6617)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(7259 7034 7516)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(4657 3983 5557)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(7259 7002 7548)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(6167 6070 6263)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(6456 6070 6970)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(6456 5974 7066)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(6488 6295 6713)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(5685 4946 6552)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(5653 5107 6424)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(7130 6841 7516)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(7130 6874 7484)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(4882 4111 5878)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(5492 4689 6681)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(4818 3983 5749)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(5139 4336 6070)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(6617 6617 6617)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(5749 4946 6841)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(5781 5107 6649)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(7291 7066 7484)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(7612 7612 7612)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(6456 6006 7066)))
						collect:
							[:each | 
							(each at: 1) value
								perform: (each at: 2)
								withArguments: (each at: 3)]))
		usingBits:
			(ByteArray fromPackedString:
					'H"H"H"H"H"H"H"H"H"H"H"H"H"H"H"H"H"H"@BH"H"H"D8P4P:HMT+PDO:$"H"H"H"H"H"H"H @"H"H"H&I[''A11";%JM+\*H"H"H"H"H"H"H"H@H"H"H"H"%F(,GHE!N$*6 2H"H"H"H"H"H"H"@BH"H"H"H)>*^*P\-XT#"XL"H"H"H"H"H"H"H @"H"H"H)$J''YY()JXI_Z@"H"H"H"H"H"H"H"H@H"H"H(B!V"QSD@ULE&(@H"H"H"H"H"H"H"H"@BH"H"H&G!%DA:M+$3]7H"H"H"H"H"H"H"H"H @"H"HTDP-K%1H)WF0Z%BH"H"H"H"H"H"H"H"H@H"H"PJ KR7.X %T5!BH"H"H"H"H"H"H"H"H"@BH"+TB0G$--[71FNT4"H"H"H"H"H"H"H"H"H @"H%)@])T^WSL"H#43H"H"H"H"H"H"H"H"H"H@H"H/U7Z:G" "H"H"H"H"H"H"H"H"H"H"H"H"@BH"VDB0%Q9)H"H"H"H"H"H"H"H"H"H"H"H"H @"H =@]* 1UBH"H"H"H"H"H"H"H"H"H"H"H"H@H"J1Q7XQB7P"H"H"H"H"H"H"H"H"H"H"H"H"@BH"X4]@]!9KHRH"H"H"H"H"H"H"H"H"H"H"H @"H&]HPGXQR7,HH"H"H"H"H&Q.#(!?H"I5#"H@H"I5QTE6*A9KA*88@:,+FAU$[(9&)8<%]RH"@BH"\E=O,ADKR7.ZC$9 ^[HUG698"*]5L7@"H @"H"I5W FUG$-;'' 8.!)F3I00-[&ZP&8L"H"H@H"H"H)J,E0-K^86=C$&Q,!T2OA-B&8L"H"H"@BH"H"H"VY,]N7.M/P8.$[J+.5B[.HL"H"H"H @"H"H"H"I5&2AQ!:U%_''J/U''N[V[0"H"H"H"H@H"H"H"H"H+15L9,BHBBL&; > 88"H"H"H"H"@@@a')