resources-icons
storeImage
	"Tools.UIMaskEditor new openOnClass: self andSelector: #storeImage"
	
	<resource: #image>
	^CachedImage
		on:
			(Image
				extent: 21 @ 21
				depth: 8
				bitsPerPixel: 8
				palette:
					(MappedPalette
						withColors:
							(#(#(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(5075 5075 5075)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(4625 5300 6295)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(4304 4304 4304)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(6070 6070 6070)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(2601 3726 5267)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(5043 5267 5589)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(2858 4047 5685)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(6327 6681 7195)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(7066 7066 7066)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(7098 7066 7034)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(5300 5300 5300)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(7387 7387 7420)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(3726 4753 6103)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(6295 6295 6295)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(4047 5075 6456)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(2987 3950 5332)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(5524 5524 5524)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(4497 5428 6649)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(3180 4304 5781)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(2987 4304 5974)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(4529 5010 5717)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(6970 6874 6713)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(5524 5717 6006)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(4207 5203 6520)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(7773 7837 7934)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(4657 5235 6038)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(3212 4400 6006)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(3758 4753 6103)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(4015 5107 6488)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(6199 6199 6199)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(2441 3854 5685)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(7901 7966 8030)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(5075 5685 6520)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(6263 6681 7323)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(3372 4111 5171)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(4946 5557 6456)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(8191 8191 8191)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(3437 4432 5781)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(7227 7323 7709)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(6167 6295 6488)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(7420 7420 7420)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(6649 6649 6649)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(3083 4304 5942)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(4914 5781 6938)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(3822 4657 5846)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(5107 5107 5107)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(5781 5781 5749)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(6874 6874 6874)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(6906 6874 6841)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(3822 4882 6295)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(4497 5235 6263)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(5364 5332 5300)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(2794 4111 5781)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(5685 5653 5653)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(5332 5332 5332)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(7098 7098 7098)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(3693 4786 6199)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(5942 6295 6745)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(6327 6327 6327)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(6713 6681 6584)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(3244 4336 5781)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(7323 7323 7323)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(4786 4786 4786)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(4240 5010 6103)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(6103 6488 7066)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(2633 3886 5524)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(6552 6552 6552)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(4015 4015 4015)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(1445 3083 5203)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(5492 6038 6809)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(2120 3404 5203)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(6424 6456 6456)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(3083 4079 5557)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(2955 4111 5653)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(5460 5653 5910)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(6874 6809 6649)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(4240 4240 4240)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(3693 4786 6231)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(3758 4786 6167)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(2216 3661 5524)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(2858 4015 5524)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(2730 3983 5685)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(3147 4015 5235)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(3822 4368 5203)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(3983 4689 5717)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(4015 4689 5685)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(6231 6231 6231)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(7741 7677 7580)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(6584 6584 6520)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(5267 5717 6392)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(6809 6777 6777)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(5107 5942 7002)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(5910 6006 6135)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(2537 3661 5235)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(6777 6681 6584)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(6713 6681 6649)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(4529 5492 6713)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(7548 7644 7837)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(7677 7677 7677)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(3501 4272 5332)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(6906 6906 6906)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(7259 7227 7227)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(3565 4593 5942)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(6841 6809 6745)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(5364 5364 5364)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(7130 7130 7130)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(6745 7098 7548)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(7163 7130 7098)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(4593 4593 4593)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(6360 6360 6360)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(6777 6713 6584)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(5589 5589 5589)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(7355 7355 7355)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(3950 4721 5781)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(6584 6584 6584)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(2569 3886 5685)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(4047 4047 4047)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(3147 4240 5749)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(6938 6906 6906)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(5814 5814 5814)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(2216 3437 5171)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(6809 6809 6809)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(5524 5685 5910)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(4272 4272 4272)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(1798 3340 5364)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(2376 3693 5428)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(2441 3693 5364)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(4786 5492 6520)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(3244 4368 5878)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(6263 6263 6263)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(5557 5492 5428)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(5171 5460 5846)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(3372 4272 5524)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(7163 7163 7130)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(3469 4497 5878)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(3726 4850 6263)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(6809 6745 6584)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(3276 4368 5878)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(7387 7387 7355)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(3597 4721 6199)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(6906 6938 6970)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(7034 7227 7548)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(3886 4978 6327)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(3886 4946 6360)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(2794 3822 5267)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(7677 7612 7516)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(2409 3822 5653)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(6456 6777 7259)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(6167 6167 6167)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(7163 7163 7163)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(6392 6392 6392)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(6392 6681 7098)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(5460 5589 5814)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(7130 7066 6970)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(7387 7387 7387)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(4850 4850 4850)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(6681 6617 6552)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(4079 4079 4079)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(5910 5846 5781)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(5846 5846 5846)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(6520 6520 6488)))
								collect:
									[:each | 
									(each at: 1) value
										perform: (each at: 2)
										withArguments: (each at: 3)]))
				usingBits:
					(ByteArray fromPackedString:
							'G1<_G1<_G1<_G1<_G1<_G1<_G1<_@@@@G1<_G1<_#T@GG1<_G1<_G1<_G1<_@@@@G1<_G1<?OH<[IRL_G1<_G1<_G1<_@@@@G1<_G21H!!][J44AG1<_G1<_G1<_@@@@G1<_HE4!I''=NDV@R$1<_G1<_G1<_@@@@G1<_L#%KEU8"C(8\\Y0;VA<_G1<_@@@@G1<_%3M\E'')S]X,1$@UJ&CT_G1<_@@@@G1<_])9*^@YICA(8Y(%FQXI%G1<_@@@@G1<_K&UWVUBGJ''MOD8ATYU)7G1<_@@@@G1<_[1"J$Q%>$$Q<TXRLZ0,-G1<_@@@@G1>V%&FLZ6-U_Q84C2^Y#FU7%!<_@@@@G1<PYX2LK3A_X4DD 6: YB>LM!<_@@@@G6V_XX2L#H1''Q5HT"JA9(JA%M&T_@@@@G659XX2L#H2L!X0I#H1$YH1%%&4_@@@@G16 #G& (JB %*BV%)Y-N%Y-''04_@@@@G8FV''62[KP)(ZF -ZF!(B"5(KV4_@@@@G8FV''0I,&25(ZF -DAA(ZF"XKS(_@@@@G8FV#JBV%#*AGYR_WI>_''9"_@@4_@@@@G1<>[@HB@ I;SI6]''Y6]P7R]^80_@@@@G1<_YX2L#H2L#H2L#H2L#H2LG1<_@@@@G1<_G1<_G1<_G1<_G1<_G1<_G1<_@@@@'))