resources
splineIconMask
	"UIMaskEditor new openOnClass: self andSelector: #splineIconMask"
	
	<resource: #image>
	^CachedImage
		on:
			(Image
				extent: 15 @ 18
				depth: 1
				bitsPerPixel: 1
				palette: CoveragePalette monoMaskPalette
				usingBits:
					#[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 62 0 0 0 127 0 0 0 227 136 0 0 193 152 0 0 193 176 0 0 193 224 0 0 227 192 0 0 127 0 0 0 62 0 0 0 12 0 0 0 24 0 0 0 48 0 0 0 96 0 0 0 0 0 0 0])