resources-icons
analysisImage
	"Tools.UIMaskEditor new openOnClass: self andSelector: #analysisImage"
	
	<resource: #image>
	^CachedImage
		on:
			(Image
				extent: 24 @ 21
				depth: 8
				bitsPerPixel: 8
				palette:
					(MappedPalette
						withColors:
							(#(#(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(5396 5396 5428)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(5653 5781 5781)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(6713 6745 6745)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(1702 1830 5749)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(2698 2698 8191)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(2666 2730 8191)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(6263 6295 6327)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(4753 4914 4914)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(7677 7709 7805)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(2537 2794 6938)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(5203 3533 3533)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(5557 5557 5460)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(1959 1959 5043)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(3854 3051 3051)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(4753 4753 4753)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(4336 2023 2280)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(6874 6841 6841)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(5717 5749 5781)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(5235 5235 5460)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(7805 7837 7901)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(3019 2601 3693)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(1927 1927 5460)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(7516 7516 7195)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(5139 5139 5332)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(2955 2794 6552)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(7066 7066 6777)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(6938 6970 7002)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(8191 2730 2376)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(5107 5107 5075)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(5524 5524 5235)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(4689 4143 4143)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(2633 2633 6392)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(6745 6745 6777)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(6777 6777 6713)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(7098 7098 7066)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(3661 3661 5332)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(5942 5974 6038)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(2762 2762 8126)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(2730 2730 8191)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(8191 8191 8191)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(8191 2730 2730)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(5524 5557 5557)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(2569 2666 8094)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(8191 2569 2569)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(5460 5428 5428)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(5749 5749 5814)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(2505 2505 4689)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(2409 2409 8191)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(3115 3083 4497)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(2023 2023 4336)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(6745 6745 6809)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(1766 1766 5846)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(6970 7163 7163)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(7452 7452 7387)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(7420 7420 7452)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(6970 6970 7034)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(7291 7323 7355)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(6199 6231 6231)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(5717 5814 5814)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(2987 2987 5749)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(4625 4047 4047)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(5589 5717 5717)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(7163 7163 7002)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(5139 4786 4786)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(8062 8094 8158)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(2505 2505 5075)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(7355 7355 7291)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(1573 1830 5364)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(5203 5589 5589)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(7934 2569 2569)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(6874 6906 6906)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(5685 5846 5846)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(4497 2826 4432)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(2473 2473 7805)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(1702 1863 5878)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(2730 2441 4272)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(5492 5171 5075)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(4946 5396 5396)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(8062 8094 8191)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(3115 3051 3950)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(4882 4304 4240)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(3340 3340 4432)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(6231 6231 6263)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(5460 5460 5492)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(3565 2473 2762)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(5781 5781 5846)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(5781 5814 5814)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(6456 6456 6488)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(5749 3019 3019)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(6777 6777 6841)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(5749 5749 5589)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(5653 5717 5717)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(4593 4593 4593)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(5589 5749 5749)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(6295 2633 2537)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(6874 2794 2794)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(8191 2633 2633)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(1573 1573 5685)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(2762 2762 6617)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(2666 2666 6809)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(2601 2601 7934)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(7773 2858 2505)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(5492 5492 5460)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(5267 5589 5589)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(2633 2633 5235)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(3983 3983 5846)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(4593 4593 4625)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(7420 7452 7548)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(5203 5300 5300)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(4336 4079 4079)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(5428 5428 5942)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(5557 5621 5621)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(4304 2441 2441)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(4529 2858 2794)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(2794 2794 7901)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(6327 6327 6135)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(6038 2633 2505)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(4818 1541 1509)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(5171 5171 5139)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(5396 5332 5075)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(4368 4400 4400)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(3983 3983 5203)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(2473 2473 6584)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(5267 5267 5300)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(1541 1541 5139)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(5203 3661 3661)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(5621 5621 5589)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(2601 2730 8191)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(3597 3308 3308)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(2666 2666 8191)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(3404 3404 4400)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(6263 6295 6263)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(5203 5203 5107)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(2633 2794 6777)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(5814 5814 5878)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(4304 4304 5589)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(6841 6841 6809)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(6809 6809 6874)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(7934 2537 2409)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(4143 4143 5589)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(6038 6038 6103)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(6456 6456 6263)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(2505 2505 7548)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(2569 2569 5107)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(4850 4850 4850)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(4882 4882 4786)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(5364 5364 4818)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(6649 2794 2794)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(6584 6617 6649)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(7869 2794 2569)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(4207 4207 4818)))
								collect:
									[:each | 
									(each at: 1) value
										perform: (each at: 2)
										withArguments: (each at: 3)]))
				usingBits:
					(ByteArray fromPackedString:
							'PDA@PDA@PDA@PDBT@CY@PDA@PDA@PDA@PDA@PDA@PDA@M2AW[E$ NDA@PDA@PDA@PDA@PDA@PC]WMDAYY$A@DBA@PDA@PDA@S$A@PD@7U3Q@PD@$$E$8PD@PHC!@PDA@PDA@F%\4PD@4U5]W[E%WVS!@PA@ PDA@IE\BH$A@PBFMMP 4Y$A@VU]YNDA@"DYSKU]@PDAW"H2BE1%3GE%@PDAYU5$8PDA;!%%@U5\4E&%:LR9Q!DAWVTA@PE%WVV,=DRQWMDA@!4$&X 1!PQI@VU]YPD@8VU]6KU]@PDH=X0P&IV UL719PDAYU5%@PDA,UU%@U0,_ RX&I''JO@4)CS41@PCQWVT@=DRQWO(,/I"X&I TIR1QTC7U0CV0FVU\\KU]@PF8;YBX&_8UHYYU^\V4< G!@PF-,KSQ@@IFRH88*FIL[JB-_O4\:[9BPIF,=UP9\GFX=GYX0]H) QP(GOVY&Y#5,Z)A*P@YVKF1&_%)7TA9X_TQ[Y&Y&Y&Y,OXY@PDA@VR5,[FY&@U5MY6Y&Y&Y&[B&CPDA@PDA@PDAYOV1,Y&Y&Y&Y&Y&1&T$A@PDA@PDA@PDA@D8$=[F1&Y&Y,[C%@PDA@PDA@PDA@PDA@PD@SVS5,[F1@PDA@PDA@PDA@PDA@PDA@PDA@PD@2A$A@PDA@PDA@PDA@'))