resources-icons
manipIcon
	"Tools.UIMaskEditor new openOnClass: self andSelector: #manipIcon"
	
	<resource: #image>
	^CachedImage
		on:
			(Image
				extent: 29 @ 21
				depth: 8
				bitsPerPixel: 8
				palette:
					(MappedPalette
						withColors:
							(#(#(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(0 0 0)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(192 321 481)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(1252 1734 2312)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(6135 6488 6906)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(6070 6070 6070)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(610 963 1413)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(2762 3790 5043)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(128 224 321)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(7837 7837 7837)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(2505 4079 6006)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(7066 7066 7066)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(5300 5300 5300)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(1927 2987 4368)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(2248 3661 5364)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(738 1188 1734)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(449 449 449)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(2441 3983 5846)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(1316 2152 3180)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(7548 7612 7709)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(2376 3886 5685)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(1060 1734 2537)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(1252 2055 3019)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(2280 3469 4882)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(7516 7516 7516)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(1863 3019 4432)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(353 546 803)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(1381 2280 3340)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(1124 1863 2698)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(674 1092 1606)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(0 32 32)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(1734 2826 4111)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(192 353 513)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(5428 5428 5428)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(1991 2120 2248)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(1477 2376 3501)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(2312 3790 5557)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(803 1316 1927)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(3115 3115 3115)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(8191 8191 8191)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(2055 3372 4914)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(4882 4882 4882)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(7420 7420 7420)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(2248 3693 5396)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(4464 5139 6038)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(931 1541 2248)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(1124 1863 2730)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(481 770 1156)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(1541 2505 3661)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(32 32 32)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(867 1445 2087)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(5749 6070 6488)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(6103 6103 6103)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(2120 3469 5107)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(7098 7098 7098)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(1863 3051 4464)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(546 899 1316)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(738 1220 1798)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(2473 4015 5878)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(8094 8094 8094)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(3501 4368 5492)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(674 1124 1638)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(2087 3180 4464)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(1284 2087 3051)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(7805 7869 7966)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(1670 2730 4015)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(5235 5235 5235)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(1606 2633 3854)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(96 160 224)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(289 481 706)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(2601 2987 3501)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(1156 1863 2762)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(481 803 1188)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(2409 3918 5749)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(867 1445 2152)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(224 385 546)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(7998 7998 7998)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(7002 7195 7484)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(2537 4143 6070)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(1027 1670 2441)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(1060 1670 2409)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(353 610 867)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(610 610 610)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(3147 3147 3147)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(4914 4914 4914)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(1413 2312 3404)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(2698 3726 5010)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(96 160 256)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(1606 2633 3886)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(7452 7452 7452)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(1606 1606 1606)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(5910 5910 5910)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(224 385 578)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(2023 3180 4593)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(1284 2120 3083)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(642 1027 1509)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(2344 3822 5621)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(5364 5364 5364)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(2698 3115 3661)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(7130 7130 7130)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(770 1252 1830)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(963 1573 2312)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(513 513 513)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(2473 4047 5942)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(481 835 1220)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(2312 3597 5235)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(2216 3629 5300)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(1349 2216 3276)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(2409 3950 5781)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(899 1477 2152)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(1060 1477 1991)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(2055 3180 4593)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(1509 2441 3565)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(192 289 417)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(385 610 899)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(2087 3404 5010)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(1895 3083 4529)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(3501 3501 3501)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(1220 2023 2955)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(5267 5267 5267)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(1798 2987 4400)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(1830 2987 4368)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(513 835 1220)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(546 835 1188)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(2184 3308 4689)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(706 1156 1702)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(2216 3629 5332)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(899 1477 2184)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(1413 1413 1413)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(385 610 931)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(4946 4946 4946)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(1798 2987 4432)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(5396 5910 6520)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(1573 2569 3758)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(96 96 96)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(256 417 610)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(449 738 1092)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(1959 3212 4721)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(642 1060 1573)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(1092 1092 1092)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(2376 3854 5653)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(1702 2794 4079)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(385 642 931)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(1252 2023 2987)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(7163 7163 7163)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(578 963 1413)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(2312 3758 5492)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(2505 4079 5974)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(3083 3083 3083)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(995 1606 2344)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(1188 1927 2826)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(2312 2312 2312)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(1381 2248 3308)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(64 96 160)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(4079 4079 4079)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(3308 3308 3308)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(2152 3565 5203)))
								collect:
									[:each | 
									(each at: 1) value
										perform: (each at: 2)
										withArguments: (each at: 3)]))
				usingBits:
					(ByteArray fromPackedString:
							'I"X&I"X&I"X&I"X)$8T@IR$&I"X&I"X&I"X&I"X@@@@&I"X&I"X&I"X&I%L@@@@@PRX&I"X&I"X&I"X&I @@@BX&I"X&I"X&I"X&O9(@@GP?I"X&I"X&I"X&I"X&@@@@I"X&I"X&I"X&I&H3&S@@&PQ"I"X&I"X&I"X&I"X@@@@&I"X&I"X&I"XKR @@@@@@@D)6I"X&I"X&I"X&I @@@BX&I"X&I"X&#0<@@@@@@@@@@D(JI"X&I"X&I"X&@@@@I"X&I"XF '']''P4$_@@@@@D)IU$]7 (JB (HFI"X@@@@&I"X&SAXIF BLBVL@@@@@_@%@@F(IBP$IRET&I @@@BX&I"ZCCGH@[@$I_@@@@@@\BP$1@C$*CP%)J2X&@@@@I"X&I#-^OH5_BP&I@@@@@@8IBY,GYB0T##4CI"X@@@@&I"X&["]2$P$IRA$@@@@@\V-+@V>HH2*NS1H&I @@@BX&I$0VBP$IBP&D@@A]# @@P%^U^BH^BT B]"X&@@@@I"X& 6 IBP$IY$\@K $I!0A9Q"JH@@ANP&E I"X@@@@&I"X;H0$IBP&L@@BDBP$/@@A$H"LQ\@A:HXD?I @@@BX&I&:RBP$IBPT@TA@IBV-P@H@-BP$XII @_6@5@@@@I"YLE $IBP%8@@ATBP$IBQ(@GR0[DF-B[P<@C9X@@@@&I(M(BP$IBS @QH,IBP$IH8X@W)^TKG9EV%&E@@@@@BX&N2LIBP$6@@A]BP$IBP$I]P@]M#Q2^3H&JUJJ@@@@I"Y.$ $IBSYD$ALIBP$IBP%_M5,XBP$6O2X&O2 @@@@&SAXIBP$IBP$IBP$IBP$IBP$IBP$IRET&I"X&N @@@BZCZ@$IBP$IBP$IBP$IBP$IBP$IBP%=J2X&I"X&@@@@'))