resources
modifyFigureIconImage
	"Tools.UIMaskEditor new openOnClass: self andSelector: #modifyFigureIconImage"
	
	<resource: #image>
	^CachedImage
		on:
			(Image
				extent: 23 @ 19
				depth: 8
				bitsPerPixel: 8
				palette:
					(MappedPalette
						withColors:
							(#(#(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(0 0 0)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(3533 3533 3533)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(6135 8191 8191)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(224 224 224)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(5010 5942 5942)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(3918 5332 5332)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(3051 4111 4111)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(4175 4047 4047)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(4946 5814 5814)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(1606 2023 2023)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(2923 3019 3019)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(3758 3597 3597)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(6488 8191 8191)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(4079 5589 5589)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(3147 3244 3244)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(4625 4657 4657)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(6360 8094 8094)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(6167 8191 8191)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(5492 6874 6874)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(2794 2762 2762)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(6809 6713 6713)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(192 256 256)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(64 321 321)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(3918 3693 3693)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(4529 5043 5043)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(2890 4047 4047)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(2955 4015 4015)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(6520 8191 8191)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(1124 1124 1124)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(2666 3501 3501)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(5010 4978 4978)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(6199 8191 8191)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(1349 1349 1349)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(5235 5203 5203)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(6649 6649 6649)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(5171 6231 6231)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(4753 4786 4786)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(4497 4914 4914)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(6552 8191 8191)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(1252 1573 1573)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(6874 6874 6874)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(6231 8191 8191)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(7934 7837 7837)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(1349 1863 1863)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(6392 6295 6295)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(481 481 481)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(417 513 513)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(3790 3629 3629)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(6552 6552 6552)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(6584 8191 8191)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(4914 5717 5717)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(4143 3950 3950)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(1670 2376 2376)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(5300 6520 6520)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(3790 3469 3469)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(6456 8094 8094)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(6263 8191 8191)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(4015 3854 3854)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(4946 4882 4882)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(4561 5075 5075)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(6424 6295 6295)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(4111 4143 4143)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(4175 4111 4111)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(8126 8094 8094)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(4529 4432 4432)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(4336 4529 4529)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(5653 5524 5524)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(5589 5557 5557)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(6617 8191 8191)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(6295 8191 8191)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(2505 2473 2473)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(3790 3822 3822)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(1573 2120 2120)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(642 931 931)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(64 64 64)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(4914 5749 5749)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(6649 8191 8191)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(578 803 803)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(7323 7195 7195)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(6327 8191 8191)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(1060 1060 1060)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(4850 5621 5621)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(1670 2248 2248)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(6006 8191 8191)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(3051 4207 4207)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(4272 4593 4593)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(4047 4047 4047)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(4111 4015 4015)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(3693 3565 3565)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(7644 7548 7548)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(4657 5235 5235)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(5043 5043 5043)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(3019 3244 3244)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(3501 3501 3501)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(2441 2376 2376)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(4529 4978 4978)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(5075 5203 5203)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(4240 5621 5621)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(3404 3726 3726)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(6392 8191 8191)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(3533 4657 4657)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(5300 6424 6424)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(224 192 192)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(1445 1734 1734)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(5010 5910 5910)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(449 578 578)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(4272 4625 4625)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(4561 4978 4978)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(7420 7355 7355)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(4721 5396 5396)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(6745 8191 8191)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(4175 4015 4015)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(96 96 96)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(1541 2023 2023)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(4464 4368 4368)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(4753 4721 4721)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(3276 3308 3308)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(2055 2762 2762)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(6424 8191 8191)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(7934 7934 7934)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(1541 1863 1863)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(7227 7130 7130)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(3758 3404 3404)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(6103 8191 8191)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(6392 6392 6392)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(4207 4175 4175)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(1477 1734 1734)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(7098 7034 7034)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(4304 4625 4625)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(7452 7355 7355)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(5557 5492 5492)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(4432 4400 4400)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(4689 5267 5267)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(3854 3533 3533)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(6456 8191 8191)))
								collect:
									[:each | 
									(each at: 1) value
										perform: (each at: 2)
										withArguments: (each at: 3)]))
				usingBits:
					(ByteArray fromPackedString:
							'@B0,R&%''_"P:U#=,Q18<KC<?KP@\ZP@@@@@@@EH7DA(J 7<"_U11BP=BY"\?HP@@D4X.]VPLG6M+M ,/^#H[I X4EU@!W@@@O2)8QQ-;@!<5BF DR1H8@#EDE @@@@@@O5$''T4<B@ H8S4UES2$BDXYTOTEAPTD@HRDNV&T)@ HBG2$)JR$)!!$>O3<?O3<@WT]=!XP8@!DBTU<XN2T@U%X?O3<?O3<@Q7=?NV48@!DBPQ\GU6<@@C<?O3<?O3<@Q61,NV48@!DBUT@*JFH@O0@?O3<?O3<@@T]VL8P8@!DB GI,L@D@O3<@O3<?O3<@V6A3]BL)@!DLZ%!"X%0@O3<?@C<?O3<@O3<TJ4TQ^3DMXHICP2D@O3<?O0@?O3<@O3=9RF96S@TJ S<?O3<@O3<?O3<@O3<@PU4SSQ4#XP*AO3<?O3<@O3<?O3<?@C<@H@@@@@AIX$8?O3<?O3<@O3<?O0@@@@@@_$(,X@A^[C<?O3<?O3<@O3<@O0@?O3<@_$(?K@A"O3<?O3<?O3<@O0@@O3<@O3<@I0@C\@A\O3<?O3<?O3<@@C<?@C<@O3<@B"\''I79AO3<?O3<?O3<@O3<?@C<?@C<@'))