resources
undoImage
	"Tools.UIMaskEditor new openOnClass: self andSelector: #undoImage"
	
	<resource: #image>
	^Image
		extent: 14 @ 17
		depth: 7
		bitsPerPixel: 8
		palette:
			(MappedPalette
				withColors:
					(#(#(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(3565 5364 6392)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(7998 7966 7998)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(3790 5139 6070)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(1830 4721 6167)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(5075 5717 6327)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(1027 3790 5621)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(963 3886 5589)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(642 3950 5685)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(3019 6327 7452)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(770 4978 6649)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(2633 4336 5589)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(6777 7066 7355)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(2344 5267 6584)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(1092 5781 7323)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(995 4593 6327)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(2312 4143 5460)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(6424 6809 7163)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(4047 5524 6424)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(3597 5524 6552)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(1252 5396 6906)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(867 5460 7066)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(2762 5781 6970)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(3597 6424 7452)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(3886 5107 6038)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(3308 6327 7516)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(4882 5781 6488)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(6938 7098 7355)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(1830 4561 6199)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(3533 5107 6070)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(3822 5043 6006)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(6745 7098 7387)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(6713 6970 7227)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(4464 5557 6327)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(2923 6135 7291)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(931 5717 7259)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(2890 5910 7227)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(3950 6552 7484)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(642 4400 6103)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(6231 6584 6970)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(2312 4753 6038)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(1477 5075 6552)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(417 3308 5139)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(1927 3886 5332)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(706 5300 6938)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(1156 3854 5653)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(1445 4882 6456)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(7130 7163 7291)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(1927 3693 5043)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(1092 3790 5460)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(835 3661 5524)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(963 5878 7420)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(3404 4818 5878)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(2376 4079 5364)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(1413 4432 5974)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(1060 5589 7291)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(546 3533 5460)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(2184 4079 5396)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(5364 6038 6617)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(1991 5107 6520)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(931 5524 7163)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(578 3437 5203)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(2248 4786 6263)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(3469 5460 6488)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(1349 4047 5621)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(1220 3918 5717)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(4946 5878 6552)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(1027 3950 5878)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(1927 4721 6167)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(6006 6456 6874)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(3276 6360 7420)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(738 3822 5814)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(5942 6392 6841)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(4175 6809 7869)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(1638 4657 6038)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(546 3886 5621)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(1284 4593 6135)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(899 3469 5203)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(3340 4786 5846)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(5428 6103 6681)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(1156 5557 7098)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(931 5653 7227)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(2441 5942 7387)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(8191 8191 8191)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(1477 5267 6745)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(1477 4015 5717)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(803 4529 6199)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(5332 6038 6681)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(2826 4497 5685)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(2537 5460 6809)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(3758 5043 6006)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(1092 4882 6552)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(1092 5942 7452)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(3693 4850 5781)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(706 4914 6584)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(7644 7677 7805)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(4143 6745 7677)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(6552 6906 7227)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(7580 7580 7644)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(4304 5524 6295)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(1252 5557 7195)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(6456 6777 7130)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(2762 5043 6199)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(2955 4721 5846)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(2890 4689 5781)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(867 5460 7034)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(1413 4047 5621)) #(ColorValue 
						#scaledRed:scaledGreen:scaledBlue: #(3918 6231 7291)))
						collect:
							[:each | 
							(each at: 1) value
								perform: (each at: 2)
								withArguments: (each at: 3)]))
		usingBits:
			(ByteArray fromPackedString:
					'@PDA@PDZ@PDA@PDA@PD@@@DA@PDPW@DA@PDA@PDA@@@A@PDA@ADA@PDA@PDA@P@@@PDAX$ >@PDA@PDA@PD@@@DANV($E! #VC5WG0DA@@@AXAI_QP !EP0CF3Q^@P@@@VYQD05[S5L:P3=TS D@@@EAV","L&!]USU)PA\A@@@A@Q1#EE@;BRTGLB03@P@@@PE!I3X(RT,NR#0EVPD@@@DA@VP-YR8&@ X)LQ$A@@@A@PDAHF\A@PDJM41 @P@@@PDA@PDD@PDAGTX8@PD@@@DA@PDA@PDA@T5BU DA@@@A@PDA@PDA@PD*C0DA@P@@@PDA@PDA@PDKK18A@PD@@@DA@PDA@PDAQD\A@PDA@@@b')