images - vector
VectorialPOV_fenceVertical
	"Returns an array containing the settings of a Situated entity vectorial pov symbol in the following order:
(color red) (color green) (color blue) (lineColor red) (lineColor green) (lineColor blue) lineWidth sizeratio position (array of outline vertices) isDistortable."
	
	^#(0.680015 0.680015 0.680015 0.0 0.0 0.0 1 1 #leftCenter #(#(357 #/ 76) #@ #(-3927 #/ 152) #(357 #/ 76) #@ #(-153 #/ 152) #(357 #/ 76) #@ #(3825 #/ 152) #(-102 #/ 19) #@ #(3825 #/ 152) #(-102 #/ 19) #@ #(-3927 #/ 152) #(357 #/ 76) #@ #(-3927 #/ 152)) true)