images - vector
VectorialPOV_man3
	"Returns an array containing the settings of a Situated entity vectorial pov symbol in the following order:
(color red) (color green) (color blue) (lineColor red) (lineColor green) (lineColor blue) lineWidth sizeratio position (array of outline vertices) isDistortable."
	
	^#(0.0 0.670004 0.670004 0.0 0.0 0.0 1 1 #center #(7.2 #@ 22.5 4.5 #@ 22.5 2.7 #@ 13.5 0.0 #@ 12.6 -2.7 #@ 13.5 -4.5 #@ 22.5 -8.1 #@ 22.5 -4.5 #@ 15.3 -12.6 #@ 12.6 -4.5 #@- 4.5 -17.1 #@ 0.0 -4.5 #@- 11.7 -4.5 #@- 15.3 -8.1 #@- 11.7 -7.2 #@- 19.8 -2.7 #@- 22.5 0.9 #@- 23.4 4.5 #@- 21.6 6.3 #@- 19.8 7.2 #@- 11.7 4.5 #@- 16.2 3.6 #@- 9.9 16.2 #@ 0.0 5.4 #@- 4.5 8.1 #@ 2.7 15.3 #@ 12.6 6.3 #@ 13.5) true)