images - vector
VectorialPOV_casa
	"Returns an array containing the settings of a Situated entity vectorial pov symbol in the following order:
(color red) (color green) (color blue) (lineColor red) (lineColor green) (lineColor blue) lineWidth sizeratio position (array of outline vertices) isDistortable."
	
	^#(0.670004 0.0 0.670004 0.0 0.0 0.0 1 1 #center #(-0.51 #@- 20.91 18.87 #@- 1.53 9.69 #@- 0.51 9.69 #@ 19.89 -11.73 #@ 19.89 -9.69 #@- 1.53 -19.89 #@- 1.53 -0.51 #@- 20.91) true)