images - vector
VectorialPOV_z_nb1
	"Returns an array containing the settings of a Situated entity vectorial pov symbol in the following order:
(color red) (color green) (color blue) (lineColor red) (lineColor green) (lineColor blue) lineWidth sizeratio position (array of outline vertices) isDistortable."
	
	^#(1.0 0.500061 0.0 0.0 0.0 0.0 1 1 #center #(3.6 #@- 23.4 11.7 #@- 23.4 11.7 #@ 22.5 3.6 #@ 22.5 3.6 #@- 14.4 -5.4 #@- 6.3 -12.6 #@- 5.4 3.6 #@- 23.4) true)