images - vector
VectorialPOV_face1
	"Returns an array containing the settings of a Situated entity vectorial pov symbol in the following order:
(color red) (color green) (color blue) (lineColor red) (lineColor green) (lineColor blue) lineWidth sizeratio position (array of outline vertices) isDistortable."
	
	^#(0.869979 0.649982 0.439995 0.0 0.0 0.0 2 1 #center #(-1.8 #@- 16.65 9.0 #@- 17.55 9.0 #@- 7.65 22.5 #@- 7.65 19.8 #@- 5.85 9.9 #@- 4.95 9.9 #@- 0.45 9.9 #@ 4.05 9.0 #@ 9.45 6.3 #@ 13.05 3.6 #@ 16.65 0.9 #@ 16.65 -2.7 #@ 16.65 -6.3 #@ 16.65 -9.0 #@ 13.05 -10.8 #@ 9.45 -12.6 #@ 4.05 -12.6 #@- 0.45 -11.7 #@- 4.95 -20.7 #@- 4.05 -23.4 #@- 7.65 -11.7 #@- 7.65 -10.8 #@- 17.55 -1.8 #@- 16.65) true)