images - vector
VectorialPOV_fenceHorizontal
	"Returns an array containing the settings of a Situated entity vectorial pov symbol in the following order:
(color red) (color green) (color blue) (lineColor red) (lineColor green) (lineColor blue) lineWidth sizeratio position (array of outline vertices) isDistortable."
	
	^#(0.680015 0.680015 0.680015 0.0 0.0 0.0 1 1 #topCenter #(22.6558 #@- 3.53077 22.6558 #@ 2.94231 -23.2442 #@ 2.94231 -23.2442 #@- 1.76538 -23.2442 #@- 3.53077 22.6558 #@- 3.53077) true)