images - vector
VectorialPOV_fish
	"Returns an array containing the settings of a Situated entity vectorial pov symbol in the following order:
(color red) (color green) (color blue) (lineColor red) (lineColor green) (lineColor blue) lineWidth sizeratio position (array of outline vertices) isDistortable."
	
	^#(0.0 0.0 1.0 0.0 0.0 0.0 1 1 #center #(-12 #@- 18 -3 #@- 17 3 #@- 13 12 #@- 5 24 #@- 13 17 #@ 2 25 #@ 17 10 #@ 8 -2 #@ 11 -17 #@ 11 -25 #@ 6 -13 #@ 2 -26 #@- 1 -24 #@- 9 -19 #@- 15) true)