images - vector
VectorialPOV_tractor
	"Returns an array containing the settings of a Situated entity vectorial pov symbol in the following order:
(color red) (color green) (color blue) (lineColor red) (lineColor green) (lineColor blue) lineWidth sizeratio position (array of outline vertices) isDistortable."
	
	^#(0.0 0.0 0.0 0.0 0.0 0.0 1 1 #center #(-10 #@ #(45 #/ 2) -14 #@ #(47 #/ 2) -18 #@ #(47 #/ 2) -21 #@ #(45 #/ 2) -22 #@ #(41 #/ 2) -24 #@ #(41 #/ 2) -25 #@ #(35 #/ 2) -26 #@ #(27 #/ 2) -25 #@ #(23 #/ 2) -22 #@ #(15 #/ 2) -22 #@ #(-13 #/ 2) 1 #@ #(-13 #/ 2) 0 #@ #(-39 #/ 2) -19 #@ #(-39 #/ 2) -18 #@ #(-15 #/ 2) -22 #@ #(-15 #/ 2) -23 #@ #(-49 #/ 2) 3 #@ #(-49 #/ 2) 5 #@ #(-3 #/ 2) 19 #@ #(-5 #/ 2) 19 #@ #(-9 #/ 2) 21 #@ #(-13 #/ 2) 23 #@ #(-11 #/ 2) 23 #@ #(-11 #/ 2) 25 #@ #(-5 #/ 2) 25 #@ #(17 #/ 2) 24 #@ #(31 #/ 2) 19 #@ #(33 #/ 2) 18 #@ #(45 #/ 2) 13 #@ #(47 #/ 2) 10 #@ #(45 #/ 2) 8 #@ #(33 #/ 2) -7 #@ #(33 #/ 2) -9 #@ #(43 #/ 2)) false)