Class {
	#name : #CMBushmeatAnthelope,
	#superclass : #CMAgentLocation,
	#instVars : [
		'age',
		'partner',
		'stage'
	],
	#category : #'Cormas-Model-BushmeatHunt-Core'
}

{ #category : #accessing }
CMBushmeatAnthelope >> age [
	^ age
]

{ #category : #accessing }
CMBushmeatAnthelope >> age: anAString [
	age := anAString
]

{ #category : #accessing }
CMBushmeatAnthelope >> partner [
	^ partner
]

{ #category : #accessing }
CMBushmeatAnthelope >> partner: anAString [
	partner := anAString
]

{ #category : #accessing }
CMBushmeatAnthelope >> stage [
	^ stage
]

{ #category : #accessing }
CMBushmeatAnthelope >> stage: anAString [
	stage := anAString
]
