Class {
	#name : #CMFrenchTranslator,
	#superclass : #CMAbstractTranslator,
	#category : #'Cormas-Core-Project'
}

{ #category : #translations }
CMFrenchTranslator >> tAbstract [

	^ 'Abstraite / Non abstraite'
]

{ #category : #translations }
CMFrenchTranslator >> tActivityDiagrams [

	^ 'Diagrammes d''activités'
]

{ #category : #translations }
CMFrenchTranslator >> tAlreadyUsed [

	^ 'Déjà utilisé !'
]

{ #category : #translations }
CMFrenchTranslator >> tAnalysis [

	^ 'Analyse'
]

{ #category : #translations }
CMFrenchTranslator >> tAppTitle [

	^ 'CORMAS'
]

{ #category : #translations }
CMFrenchTranslator >> tApply [

	^ 'Appliquer'
]

{ #category : #translations }
CMFrenchTranslator >> tAttributes [

	^ 'Attributs'
]

{ #category : #translations }
CMFrenchTranslator >> tAttributesSuperLabel [

	^ 'Attributs et variables de classe des super classes'
]

{ #category : #translations }
CMFrenchTranslator >> tAttributesTargetLabel [

	^ 'Attributs et classe Variables de la classe cible'
]

{ #category : #translations }
CMFrenchTranslator >> tCellAutomatonHelp [

	^ 'CA est utile pour la dynamique entre les cellules'
]

{ #category : #translations }
CMFrenchTranslator >> tClassifyByParams [

	^ 'Classer par Paramètres'
]

{ #category : #translations }
CMFrenchTranslator >> tCommunication [

	^ 'Communication'
]

{ #category : #translations }
CMFrenchTranslator >> tCreateAgent [

	^ 'Créer une sorte d''agent'
]

{ #category : #translations }
CMFrenchTranslator >> tCreateEntityKind [

	^ 'Créer un type d''entité'
]

{ #category : #translations }
CMFrenchTranslator >> tCreateInstances [

	^ 'Créer des instances'
]

{ #category : #translations }
CMFrenchTranslator >> tCreationDate [

	^ 'Date de création'
]

{ #category : #translations }
CMFrenchTranslator >> tCrossSensAnalysis [

	^ 'Analyse de sensibilité croisée'
]

{ #category : #translations }
CMFrenchTranslator >> tDefineEntities [

	^ 'Définir les entités'
]

{ #category : #translations }
CMFrenchTranslator >> tDisplayParams [

	^ 'Paramètres d''Affichage'
]

{ #category : #translations }
CMFrenchTranslator >> tEdit [

	^ 'Éditer'
]

{ #category : #translations }
CMFrenchTranslator >> tEnterAttName [

	^ 'Entrez un nom d''attribut (sans espaces blancs, chiffres ou symboles)'
]

{ #category : #translations }
CMFrenchTranslator >> tFullNetwork [

	^ 'Réseau complet'
]

{ #category : #translations }
CMFrenchTranslator >> tGroup [

	^ 'Groupe'
]

{ #category : #translations }
CMFrenchTranslator >> tHelpAddInstAtt [

	^ 'Ajouter un nouvel attribut à la instance cible'
]

{ #category : #translations }
CMFrenchTranslator >> tHelpRemoveInstAtt [

	^ 'Supprimer un attribut de la instance cible'
]

{ #category : #translations }
CMFrenchTranslator >> tInitInstantiation [

	^ 'l''instanciation initiale'
]

{ #category : #translations }
CMFrenchTranslator >> tInvalidName [

	^ ' n''est pas un nom valide. Merci d''entrer un nom valide'
]

{ #category : #translations }
CMFrenchTranslator >> tLocatedObjectHelp [

	^ 'Une entité passive située sur une cellule'
]

{ #category : #translations }
CMFrenchTranslator >> tLocation [

	^ 'Location'
]

{ #category : #translations }
CMFrenchTranslator >> tManipulateInstances [

	^ 'Manipuler les instances'
]

{ #category : #translations }
CMFrenchTranslator >> tMessage [

	^ 'Message'
]

{ #category : #translations }
CMFrenchTranslator >> tMessages [

	^ 'Messages'
]

{ #category : #translations }
CMFrenchTranslator >> tMessagesProgramming [

	^ 'Configuration de Messages'
]

{ #category : #translations }
CMFrenchTranslator >> tMethods [

	^ 'Méthodes'
]

{ #category : #translations }
CMFrenchTranslator >> tModelComments [

	^ 'Commentaires sur le modèle'
]

{ #category : #translations }
CMFrenchTranslator >> tModelListing [

	^ 'Liste de modèles fichier texte'
]

{ #category : #translations }
CMFrenchTranslator >> tMonteCarlo [

	^ 'Monte Carlo'
]

{ #category : #translations }
CMFrenchTranslator >> tName [

	^ 'Nom'
]

{ #category : #translations }
CMFrenchTranslator >> tNetworkArc [

	^ 'Réseau Arc'
]

{ #category : #translations }
CMFrenchTranslator >> tNetworkArcHelp [

	^ 'Un Arc de Réseau situé sur 2 Cellules'
]

{ #category : #translations }
CMFrenchTranslator >> tNetworkNode [

	^ 'Nœud de réseau'
]

{ #category : #translations }
CMFrenchTranslator >> tNetworkNodeHelp [

	^ 'Un nœud d''un réseau situé sur une cellule'
]

{ #category : #translations }
CMFrenchTranslator >> tOATPredefValues [

	^ 'Prédéfini par liste de valeurs'
]

{ #category : #translations }
CMFrenchTranslator >> tObject [

	^ 'Objet'
]

{ #category : #translations }
CMFrenchTranslator >> tObjectHelp [

	^ 'Une simple entité passive'
]

{ #category : #translations }
CMFrenchTranslator >> tPoV [

	^ 'PoV'
]

{ #category : #translations }
CMFrenchTranslator >> tProbesProgramming [

	^ 'Configuration de Probes'
]

{ #category : #translations }
CMFrenchTranslator >> tProgrammingEntityClass [

	^ 'la classe pour chaque entité...'
]

{ #category : #translations }
CMFrenchTranslator >> tRemove [

	^ 'Supprimer'
]

{ #category : #translations }
CMFrenchTranslator >> tScheduler [

	^ 'le planificateur'
]

{ #category : #translations }
CMFrenchTranslator >> tSimInformation [

	^ 'Informations sur la simulation'
]

{ #category : #translations }
CMFrenchTranslator >> tSimInterface [

	^ 'Interface de Simulation'
]

{ #category : #translations }
CMFrenchTranslator >> tSimOrganization [

	^ 'l''organisation de la simulation...'
]

{ #category : #translations }
CMFrenchTranslator >> tSimpleCellHelp [

	^ 'SpatialEntityElement est l''entité Cell de base'
]

{ #category : #translations }
CMFrenchTranslator >> tSimpleStochAnalysis [

	^ 'Analyse Stochastique Simple'
]

{ #category : #translations }
CMFrenchTranslator >> tSimulation [

	^ 'Simulation'
]

{ #category : #translations }
CMFrenchTranslator >> tSocial [

	^ 'Social'
]

{ #category : #translations }
CMFrenchTranslator >> tSpace [

	^ 'Espace'
]

{ #category : #translations }
CMFrenchTranslator >> tSpaceEntities [

	^ 'Espace et Entités'
]

{ #category : #translations }
CMFrenchTranslator >> tSpecialize [

	^ 'Spécialiser'
]
