Class {
	#name : #CMNorwegianTranslator,
	#superclass : #CMAbstractTranslator,
	#category : #'Cormas-Core-Project'
}

{ #category : #translations }
CMNorwegianTranslator >> tAbout [

	^ 'Om'
]

{ #category : #translations }
CMNorwegianTranslator >> tAboutModel [

	^ 'Om denne modellen'
]

{ #category : #translations }
CMNorwegianTranslator >> tAbstract [

	^ 'Sammendrag / Ikke noe sammendrag'
]

{ #category : #translations }
CMNorwegianTranslator >> tActivityDiagrams [

	^ 'Aktivitetsdiagrammer'
]

{ #category : #translations }
CMNorwegianTranslator >> tAddSymbols [

	^ 'Vil du opprette symbolene som er knyttet til disse verdiene?'
]

{ #category : #translations }
CMNorwegianTranslator >> tAlreadyUsed [

	^ 'Allerede brukt!!!'
]

{ #category : #translations }
CMNorwegianTranslator >> tAnalysis [

	^ 'Analyse'
]

{ #category : #translations }
CMNorwegianTranslator >> tAppTitle [

	^ 'CORMAS'
]

{ #category : #translations }
CMNorwegianTranslator >> tApply [

	^ 'Søke'
]

{ #category : #translations }
CMNorwegianTranslator >> tArray [

	^ 'Matrise'
]

{ #category : #translations }
CMNorwegianTranslator >> tAttributes [

	^ 'Attributter'
]

{ #category : #translations }
CMNorwegianTranslator >> tAttributesSuperLabel [

	^ 'Attributter og klassevariabler for superklassene'
]

{ #category : #translations }
CMNorwegianTranslator >> tAttributesTargetLabel [

	^ 'Attributter og klassevariabler for målklassen'
]

{ #category : #translations }
CMNorwegianTranslator >> tBackwardLabel [

	^ 'Bakover'
]

{ #category : #translations }
CMNorwegianTranslator >> tBoolean [

	^ 'Boolsk'
]

{ #category : #translations }
CMNorwegianTranslator >> tBrowseModel [

	^ 'Bla gjennom scoped-modellen'
]

{ #category : #translations }
CMNorwegianTranslator >> tCORMASBrowser [

	^ 'CORMAS-nettleser'
]

{ #category : #translations }
CMNorwegianTranslator >> tCancel [

	^ 'Avbryt'
]

{ #category : #translations }
CMNorwegianTranslator >> tCellAutomatonHelp [

	^ 'CA er nyttig for dynamikken mellom celler.'
]

{ #category : #translations }
CMNorwegianTranslator >> tCellularAutomaton [

	^ 'Cellular Automaton'
]

{ #category : #translations }
CMNorwegianTranslator >> tChange [

	^ 'Endring'
]

{ #category : #translations }
CMNorwegianTranslator >> tChangeColor [

	^ 'Endre farge'
]

{ #category : #translations }
CMNorwegianTranslator >> tChangeModelComments [

	^ 'Endre modell Kommentarer'
]

{ #category : #translations }
CMNorwegianTranslator >> tChooseColor [

	^ 'Velg en farge'
]

{ #category : #translations }
CMNorwegianTranslator >> tChooseDumpDir [

	^ 'Velg en "Dump"-katalog:'
]

{ #category : #translations }
CMNorwegianTranslator >> tChooseStFile [

	^ 'Velg st-fil'
]

{ #category : #translations }
CMNorwegianTranslator >> tChooseTokenColor [

	^ 'Velg farge på symbolet'
]

{ #category : #translations }
CMNorwegianTranslator >> tClassifyByParams [

	^ 'Klassifisere etter parametere'
]

{ #category : #translations }
CMNorwegianTranslator >> tClose [

	^ 'Lukk'
]

{ #category : #translations }
CMNorwegianTranslator >> tCollectionEmpty [

	^ 'Samling (tom)'
]

{ #category : #translations }
CMNorwegianTranslator >> tCommunication [

	^ 'Kommunikasjon'
]

{ #category : #translations }
CMNorwegianTranslator >> tConfirmAbstractEntity [

	^ ' er abstrakt. Den vil bli endret til en konkret klasse. Er det greit?'
]

{ #category : #translations }
CMNorwegianTranslator >> tConfirmBeforeLaunch [

	^ 'Bekreftelse før lansering'
]

{ #category : #translations }
CMNorwegianTranslator >> tConfirmConcreteEntity [

	^ ' er konkret. Den vil bli endret til en abstrakt klasse. Er det greit?'
]

{ #category : #translations }
CMNorwegianTranslator >> tConfirmDeleteAttribute [

	^ 'Er du sikker på at du vil fjerne det valgte attributtet'
]

{ #category : #translations }
CMNorwegianTranslator >> tConfirmDeleteEntity [

	^ 'Er du sikker på at du vil fjerne den valgte enheten'
]

{ #category : #translations }
CMNorwegianTranslator >> tCreateAgent [

	^ 'Opprett en slags agent'
]

{ #category : #translations }
CMNorwegianTranslator >> tCreateEntityKind [

	^ 'Opprett en type Entitet'
]

{ #category : #translations }
CMNorwegianTranslator >> tCreateInstances [

	^ 'Opprett instanser'
]

{ #category : #translations }
CMNorwegianTranslator >> tCreatePoVAtt [

	^ 'Opprett PoV på hvilket attributt?'
]

{ #category : #translations }
CMNorwegianTranslator >> tCreationDate [

	^ 'Dato for opprettelse'
]

{ #category : #translations }
CMNorwegianTranslator >> tCrossSensAnalysis [

	^ 'Krysset følsomhetsanalyse'
]

{ #category : #translations }
CMNorwegianTranslator >> tCrossedPredefValues [

	^ 'Krysset forhåndsdefinert av liste over verdier'
]

{ #category : #translations }
CMNorwegianTranslator >> tCrossedSeqValues [

	^ 'Kryssede sekvensielle verdier'
]

{ #category : #translations }
CMNorwegianTranslator >> tCurrentStep [

	^ 'gjeldende trinn'
]

{ #category : #translations }
CMNorwegianTranslator >> tDefineControl4Scenario [

	^ 'Definer minst én kontrollmetode for utarbeidelse av et scenario.'
]

{ #category : #translations }
CMNorwegianTranslator >> tDefineEntities [

	^ 'Definere enhetene'
]

{ #category : #translations }
CMNorwegianTranslator >> tDefineInit4Scenario [

	^ 'Definer minst én init-metode for å forberede et scenario.'
]

{ #category : #translations }
CMNorwegianTranslator >> tDeveloperTools [

	^ 'Verktøy for utviklere'
]

{ #category : #translations }
CMNorwegianTranslator >> tDisplayLegends [

	^ 'Vis legender'
]

{ #category : #translations }
CMNorwegianTranslator >> tDisplayModelVersions [

	^ 'Visning av modellversjoner'
]

{ #category : #translations }
CMNorwegianTranslator >> tDisplayParams [

	^ 'Visning av parametere'
]

{ #category : #translations }
CMNorwegianTranslator >> tDistributeAsClient [

	^ 'Distribuere (fungere som en klient)'
]

{ #category : #translations }
CMNorwegianTranslator >> tDistributeAsServer [

	^ 'Distribuere (fungere som en server)'
]

{ #category : #translations }
CMNorwegianTranslator >> tEdit [

	^ 'Redigere'
]

{ #category : #translations }
CMNorwegianTranslator >> tEditActivityDiagrams [

	^ 'redigere aktivitetsdiagrammer'
]

{ #category : #translations }
CMNorwegianTranslator >> tEditAttributes [

	^ 'redigere attributter'
]

{ #category : #translations }
CMNorwegianTranslator >> tEditInit [

	^ 'redigere initialisering'
]

{ #category : #translations }
CMNorwegianTranslator >> tEditSteps [

	^ 'redigere trinn'
]

{ #category : #translations }
CMNorwegianTranslator >> tEnableStepBack [

	^ 'Gjør det mulig å gå tilbake'
]

{ #category : #translations }
CMNorwegianTranslator >> tEnterAttName [

	^ 'Skriv inn et attributtnavn (uten mellomrom, tall eller symboler).'
]

{ #category : #translations }
CMNorwegianTranslator >> tEntities [

	^ 'Enheter'
]

{ #category : #translations }
CMNorwegianTranslator >> tExplore [

	^ 'Utforsk'
]

{ #category : #translations }
CMNorwegianTranslator >> tFile [

	^ 'Fil'
]

{ #category : #translations }
CMNorwegianTranslator >> tFillArray [

	^ 'Fyll Array med verdier'
]

{ #category : #translations }
CMNorwegianTranslator >> tFinalStep [

	^ 'siste trinn'
]

{ #category : #translations }
CMNorwegianTranslator >> tFinalStepChoice [

	^ 'Siste trinn:'
]

{ #category : #translations }
CMNorwegianTranslator >> tFixRandomSeed [

	^ 'Fastsett det tilfeldige frøet til'
]

{ #category : #translations }
CMNorwegianTranslator >> tForwardLabel [

	^ 'Fremover'
]

{ #category : #translations }
CMNorwegianTranslator >> tFullNetwork [

	^ 'Hele nettverket'
]

{ #category : #translations }
CMNorwegianTranslator >> tFullNetworkHelp [

	^ 'Et orientert nettverk som består av et sett med buer og noder.'
]

{ #category : #translations }
CMNorwegianTranslator >> tGetterAccessor [

	^ 'Getter-tilgang'
]

{ #category : #translations }
CMNorwegianTranslator >> tGroup [

	^ 'Gruppe'
]

{ #category : #translations }
CMNorwegianTranslator >> tHelp [

	^ 'Hjelp'
]

{ #category : #translations }
CMNorwegianTranslator >> tHelpAddClassAttr [

	^ 'Legg til et nytt klasseattributt i målklassen'
]

{ #category : #translations }
CMNorwegianTranslator >> tHelpAddInstAtt [

	^ 'Legg til et nytt attributt i målklassen'
]

{ #category : #translations }
CMNorwegianTranslator >> tHelpRemoveInstAtt [

	^ 'Fjern et attributt fra målklassen'
]

{ #category : #translations }
CMNorwegianTranslator >> tHowToRunModel [

	^ 'Slik kjører du denne modellen'
]

{ #category : #translations }
CMNorwegianTranslator >> tInitInstantiation [

	^ 'den første instansieringen'
]

{ #category : #translations }
CMNorwegianTranslator >> tInitialValueChooser [

	^ 'Valg av startverdi'
]

{ #category : #translations }
CMNorwegianTranslator >> tInitialValueLabel [

	^ 'Angi en startverdi for dette attributtet'
]

{ #category : #translations }
CMNorwegianTranslator >> tInitialize [

	^ 'Initialiser'
]

{ #category : #translations }
CMNorwegianTranslator >> tInitializeRandomness [

	^ 'Initialisere tilfeldighet'
]

{ #category : #translations }
CMNorwegianTranslator >> tInspectModel [

	^ 'Inspiser modellen'
]

{ #category : #translations }
CMNorwegianTranslator >> tInvalidName [

	^ ' er ikke et gyldig navn. Vennligst skriv inn et gyldig navn'
]

{ #category : #translations }
CMNorwegianTranslator >> tLanguage [

	^ 'Språk'
]

{ #category : #translations }
CMNorwegianTranslator >> tLocalImage [

	^ 'Lokalt bilde'
]

{ #category : #translations }
CMNorwegianTranslator >> tLocalStorage [

	^ 'Lokal diskett'
]

{ #category : #translations }
CMNorwegianTranslator >> tLocatedObject [

	^ 'Lokalisert objekt'
]

{ #category : #translations }
CMNorwegianTranslator >> tLocatedObjectHelp [

	^ 'En passiv enhet som befinner seg på en celle'
]

{ #category : #translations }
CMNorwegianTranslator >> tLocation [

	^ 'Beliggenhet'
]

{ #category : #translations }
CMNorwegianTranslator >> tManipulateInstances [

	^ 'Manipulere forekomster'
]

{ #category : #translations }
CMNorwegianTranslator >> tMessage [

	^ 'Melding'
]

{ #category : #translations }
CMNorwegianTranslator >> tMessageHelp [

	^ 'Melding for AgentCommunication (med postkasse)'
]

{ #category : #translations }
CMNorwegianTranslator >> tMessages [

	^ 'Meldinger'
]

{ #category : #translations }
CMNorwegianTranslator >> tMessagesProgramming [

	^ 'Programmering av meldinger'
]

{ #category : #translations }
CMNorwegianTranslator >> tMethods [

	^ 'Metoder'
]

{ #category : #translations }
CMNorwegianTranslator >> tMissingControlMethods [

	^ 'Modellen definerer ingen metode for kontroll!'
]

{ #category : #translations }
CMNorwegianTranslator >> tMissingInitMethods [

	^ 'Modellen definerer ingen metode for initialisering !'
]

{ #category : #translations }
CMNorwegianTranslator >> tModelComments [

	^ 'Modell Kommentarer'
]

{ #category : #translations }
CMNorwegianTranslator >> tModelGlossary [

	^ 'Ordliste for modeller'
]

{ #category : #translations }
CMNorwegianTranslator >> tModelListing [

	^ 'Modelloversikt som tekstfil'
]

{ #category : #translations }
CMNorwegianTranslator >> tModifiedModelName [

	^ 'Navnet har blitt omdøpt til'
]

{ #category : #translations }
CMNorwegianTranslator >> tMonteCarlo [

	^ 'Monte Carlo'
]

{ #category : #translations }
CMNorwegianTranslator >> tName [

	^ 'Navn'
]

{ #category : #translations }
CMNorwegianTranslator >> tNetworkArc [

	^ 'Nettverksbue'
]

{ #category : #translations }
CMNorwegianTranslator >> tNetworkArcHelp [

	^ 'En lysbue i et nettverk som befinner seg på 2 celler'
]

{ #category : #translations }
CMNorwegianTranslator >> tNetworkNode [

	^ 'Nettverksnode'
]

{ #category : #translations }
CMNorwegianTranslator >> tNetworkNodeHelp [

	^ 'En node i et nettverk som befinner seg på en celle.'
]

{ #category : #translations }
CMNorwegianTranslator >> tNew [

	^ 'Ny'
]

{ #category : #translations }
CMNorwegianTranslator >> tNewEntity [

	^ 'Ny enhet'
]

{ #category : #translations }
CMNorwegianTranslator >> tNewProjectInvalidName [

	^ 'Prosjektnavnet er ugyldig. Vennligst prøv igjen'
]

{ #category : #translations }
CMNorwegianTranslator >> tNewProjectName [

	^ 'Nytt prosjektnavn'
]

{ #category : #translations }
CMNorwegianTranslator >> tNoStoredSim [

	^ '"Dump"-katalogen inneholder ikke lagrede simuleringer.'
]

{ #category : #translations }
CMNorwegianTranslator >> tNoStoredSimFolder [

	^ ' katalogen inneholder ikke lagrede simuleringer'
]

{ #category : #translations }
CMNorwegianTranslator >> tNoValue [

	^ 'Ingen verdi eller en annen instans (sendes i #init)'
]

{ #category : #translations }
CMNorwegianTranslator >> tNoVersion [

	^ 'Ingen versjon'
]

{ #category : #translations }
CMNorwegianTranslator >> tNotifyObs [

	^ 'Varsle observatører ved endringer'
]

{ #category : #translations }
CMNorwegianTranslator >> tNumber [

	^ 'Antall'
]

{ #category : #translations }
CMNorwegianTranslator >> tNumberOfEntities [

	^ 'Antall enheter'
]

{ #category : #translations }
CMNorwegianTranslator >> tOATPredefValues [

	^ 'Forhåndsdefinert av liste over verdier'
]

{ #category : #translations }
CMNorwegianTranslator >> tOATSensAnalysis [

	^ 'Følsomhetsanalyse av OAT'
]

{ #category : #translations }
CMNorwegianTranslator >> tOATSeqValues [

	^ 'Sekvensielle verdier'
]

{ #category : #translations }
CMNorwegianTranslator >> tObject [

	^ 'Objekt'
]

{ #category : #translations }
CMNorwegianTranslator >> tObjectHelp [

	^ 'En enkel passiv enhet'
]

{ #category : #translations }
CMNorwegianTranslator >> tObserver [

	^ 'Observatøren...'
]

{ #category : #translations }
CMNorwegianTranslator >> tOk [

	^ 'Ok'
]

{ #category : #translations }
CMNorwegianTranslator >> tOpen [

	^ 'Åpen'
]

{ #category : #translations }
CMNorwegianTranslator >> tOpenCormasIssue [

	^ 'Åpne et problem'
]

{ #category : #translations }
CMNorwegianTranslator >> tOpenPharoMenu [

	^ 'Åpne Pharo-menyen'
]

{ #category : #translations }
CMNorwegianTranslator >> tPackageDepedenciesGraph [

	^ 'Åpne grafen for pakkeavhengigheter'
]

{ #category : #translations }
CMNorwegianTranslator >> tPackageDepedenciesTool [

	^ 'Analysator for åpne pakkeavhengigheter'
]

{ #category : #translations }
CMNorwegianTranslator >> tPassive [

	^ 'Passiv'
]

{ #category : #translations }
CMNorwegianTranslator >> tPhoto [

	^ 'Foto'
]

{ #category : #translations }
CMNorwegianTranslator >> tPoV [

	^ 'PoV'
]

{ #category : #translations }
CMNorwegianTranslator >> tPoVDefinition [

	^ 'Definisjon av PoV'
]

{ #category : #translations }
CMNorwegianTranslator >> tPoVInfoDisplayed [

	^ 'Informasjon som skal vises'
]

{ #category : #translations }
CMNorwegianTranslator >> tPoVListInfo [

	^ 'Metoder som returnerer en streng'
]

{ #category : #translations }
CMNorwegianTranslator >> tPoVListMethods [

	^ 'Metoder som returnerer en farge eller et symbol'
]

{ #category : #translations }
CMNorwegianTranslator >> tPoVListSymbols [

	^ 'Tilhørende symboler'
]

{ #category : #translations }
CMNorwegianTranslator >> tPoVSetColor [

	^ 'Angi farge'
]

{ #category : #translations }
CMNorwegianTranslator >> tPoVSetter [

	^ 'PoV Setter'
]

{ #category : #translations }
CMNorwegianTranslator >> tProbes [

	^ 'Sonder'
]

{ #category : #translations }
CMNorwegianTranslator >> tProbesProgramming [

	^ 'Sondeinnstiller'
]

{ #category : #translations }
CMNorwegianTranslator >> tProgramming [

	^ 'Programmering'
]

{ #category : #translations }
CMNorwegianTranslator >> tProgrammingEntityClass [

	^ 'klassen for hver Entity...'
]

{ #category : #translations }
CMNorwegianTranslator >> tProjectOpenFailed [

	^ 'Prosjektet ble ikke åpnet, vennligst prøv igjen'
]

{ #category : #translations }
CMNorwegianTranslator >> tProperties [

	^ 'Egenskaper'
]

{ #category : #translations }
CMNorwegianTranslator >> tQuerySaveProject [

	^ 'Prosjektet ble endret, vil du lagre?'
]

{ #category : #translations }
CMNorwegianTranslator >> tQuit [

	^ 'Slutt'
]

{ #category : #translations }
CMNorwegianTranslator >> tRandom [

	^ 'Tilfeldig'
]

{ #category : #translations }
CMNorwegianTranslator >> tReleaseRandomSeed [

	^ 'Slipp tilfeldig frø etter initialisering'
]

{ #category : #translations }
CMNorwegianTranslator >> tRemoteImage [

	^ 'Eksternt bilde'
]

{ #category : #translations }
CMNorwegianTranslator >> tRemove [

	^ 'Fjern'
]

{ #category : #translations }
CMNorwegianTranslator >> tRename [

	^ 'Gi nytt navn'
]

{ #category : #translations }
CMNorwegianTranslator >> tRenameEntityDialogText [

	^ 'Skriv inn enhetens navn:'
]

{ #category : #translations }
CMNorwegianTranslator >> tReplay [

	^ 'avspilling'
]

{ #category : #translations }
CMNorwegianTranslator >> tReplayStartStep [

	^ 'Avspillingen starter ved trinn'
]

{ #category : #translations }
CMNorwegianTranslator >> tRunCormasTests [

	^ 'Kjøre CORMAS-tester'
]

{ #category : #translations }
CMNorwegianTranslator >> tSave [

	^ 'Lagre'
]

{ #category : #translations }
CMNorwegianTranslator >> tSaveAs [

	^ 'Lagre som'
]

{ #category : #translations }
CMNorwegianTranslator >> tScheduler [

	^ 'Planleggeren'
]

{ #category : #translations }
CMNorwegianTranslator >> tSelectControlMethod [

	^ 'Velg en kontrollmetode'
]

{ #category : #translations }
CMNorwegianTranslator >> tSelectInitMethod [

	^ 'Velg en metode for initialisering'
]

{ #category : #translations }
CMNorwegianTranslator >> tSelectMethod [

	^ 'Velg en metode for'
]

{ #category : #translations }
CMNorwegianTranslator >> tSelectProbesToRecord [

	^ 'Velg prober som skal registreres'
]

{ #category : #translations }
CMNorwegianTranslator >> tSetterAccessor [

	^ 'Setter accessor'
]

{ #category : #translations }
CMNorwegianTranslator >> tSimCloseHelp [

	^ 'Lukk simuleringsgrensesnittet'
]

{ #category : #translations }
CMNorwegianTranslator >> tSimFinalStepHelp [

	^ 'Gå inn i det siste trinnet'
]

{ #category : #translations }
CMNorwegianTranslator >> tSimInformation [

	^ 'Informasjon om simulering'
]

{ #category : #translations }
CMNorwegianTranslator >> tSimInterface [

	^ 'Simuleringsgrensesnitt'
]

{ #category : #translations }
CMNorwegianTranslator >> tSimOrganization [

	^ 'simuleringsorganisasjonen...'
]

{ #category : #translations }
CMNorwegianTranslator >> tSimStepHelp [

	^ 'Gjeldende tid'
]

{ #category : #translations }
CMNorwegianTranslator >> tSimpleCell [

	^ 'Enkel celle'
]

{ #category : #translations }
CMNorwegianTranslator >> tSimpleCellHelp [

	^ 'SpatialEntityElement er den grunnleggende Cell-entiteten.'
]

{ #category : #translations }
CMNorwegianTranslator >> tSimpleStochAnalysis [

	^ 'Enkel stokastisk analyse'
]

{ #category : #translations }
CMNorwegianTranslator >> tSimulate [

	^ 'simulere'
]

{ #category : #translations }
CMNorwegianTranslator >> tSimulation [

	^ 'Simulering'
]

{ #category : #translations }
CMNorwegianTranslator >> tSnapshot [

	^ 'Øyeblikksbilde av nåværende tilstand'
]

{ #category : #translations }
CMNorwegianTranslator >> tSocial [

	^ 'Sosialt'
]

{ #category : #translations }
CMNorwegianTranslator >> tSpace [

	^ 'Romfart'
]

{ #category : #translations }
CMNorwegianTranslator >> tSpaceEntities [

	^ 'Rom og enheter'
]

{ #category : #translations }
CMNorwegianTranslator >> tSpaceInterface [

	^ 'Romgrensesnitt'
]

{ #category : #translations }
CMNorwegianTranslator >> tSpatial [

	^ 'Romlig'
]

{ #category : #translations }
CMNorwegianTranslator >> tSpecialization [

	^ 'Spesialisering'
]

{ #category : #translations }
CMNorwegianTranslator >> tSpecialize [

	^ 'Spesialisere seg'
]

{ #category : #translations }
CMNorwegianTranslator >> tSpecializeEntityDialogText [

	^ 'Opprett en ny type enhet: Vennligst skriv inn enhetens navn'
]

{ #category : #translations }
CMNorwegianTranslator >> tStFiles [

	^ 'st-filer'
]

{ #category : #translations }
CMNorwegianTranslator >> tStartRWebService [

	^ 'Start webtjeneste for R'
]

{ #category : #translations }
CMNorwegianTranslator >> tStopRWebService [

	^ 'Stoppe webtjenesten for R'
]

{ #category : #translations }
CMNorwegianTranslator >> tStringSymbol [

	^ 'Streng/symbol'
]

{ #category : #translations }
CMNorwegianTranslator >> tTools [

	^ 'Verktøy'
]

{ #category : #translations }
CMNorwegianTranslator >> tUsefulExpressions [

	^ 'Nyttige uttrykk'
]

{ #category : #translations }
CMNorwegianTranslator >> tValidNameRequired [

	^ 'Vennligst oppgi et gyldig navn'
]

{ #category : #translations }
CMNorwegianTranslator >> tVersionName [

	^ 'Navn på versjon'
]

{ #category : #translations }
CMNorwegianTranslator >> tVideo [

	^ 'Video'
]

{ #category : #translations }
CMNorwegianTranslator >> tVisualization [

	^ 'Visualisering'
]

{ #category : #translations }
CMNorwegianTranslator >> tWhichModel [

	^ 'Hvilken modell?'
]

{ #category : #translations }
CMNorwegianTranslator >> tWhichOpeningLocation [

	^ 'Velg åpen plassering'
]
