Class {
	#name : #CMPolishTranslator,
	#superclass : #CMAbstractTranslator,
	#category : #'Cormas-Core-Project'
}

{ #category : #translations }
CMPolishTranslator >> tAbout [

	^ 'O'
]

{ #category : #translations }
CMPolishTranslator >> tAboutModel [

	^ 'Informacje o tym modelu'
]

{ #category : #translations }
CMPolishTranslator >> tAbstract [

	^ 'Streszczenie / Brak streszczenia'
]

{ #category : #translations }
CMPolishTranslator >> tActivityDiagrams [

	^ 'Diagramy aktywności'
]

{ #category : #translations }
CMPolishTranslator >> tAddSymbols [

	^ 'Czy chcesz utworzyć symbole powiązane z tymi wartościami?'
]

{ #category : #translations }
CMPolishTranslator >> tAlreadyUsed [

	^ 'Już używane!!!'
]

{ #category : #translations }
CMPolishTranslator >> tAnalysis [

	^ 'Analiza'
]

{ #category : #translations }
CMPolishTranslator >> tAppTitle [

	^ 'CORMAS'
]

{ #category : #translations }
CMPolishTranslator >> tApply [

	^ 'Zastosuj'
]

{ #category : #translations }
CMPolishTranslator >> tArray [

	^ 'Tablica'
]

{ #category : #translations }
CMPolishTranslator >> tAttributes [

	^ 'Atrybuty'
]

{ #category : #translations }
CMPolishTranslator >> tAttributesSuperLabel [

	^ 'Atrybuty i zmienne klasowe nadklas'
]

{ #category : #translations }
CMPolishTranslator >> tAttributesTargetLabel [

	^ 'Atrybuty i zmienne klasowe klasy docelowej'
]

{ #category : #translations }
CMPolishTranslator >> tAuthors [

	^ 'Autorzy'
]

{ #category : #translations }
CMPolishTranslator >> tBackwardLabel [

	^ 'Do tyłu'
]

{ #category : #translations }
CMPolishTranslator >> tBoolean [

	^ 'Wartość logiczna'
]

{ #category : #translations }
CMPolishTranslator >> tBrowseModel [

	^ 'Przeglądaj model z zakresem'
]

{ #category : #translations }
CMPolishTranslator >> tCORMASBrowser [

	^ 'Przeglądarka CORMAS'
]

{ #category : #translations }
CMPolishTranslator >> tCancel [

	^ 'Anuluj'
]

{ #category : #translations }
CMPolishTranslator >> tCellAutomatonHelp [

	^ 'CA jest przydatny dla dynamiki między komórkami'
]

{ #category : #translations }
CMPolishTranslator >> tCellularAutomaton [

	^ 'Automat komórkowy'
]

{ #category : #translations }
CMPolishTranslator >> tChange [

	^ 'Zmiana'
]

{ #category : #translations }
CMPolishTranslator >> tChangeColor [

	^ 'Zmień kolor'
]

{ #category : #translations }
CMPolishTranslator >> tChangeModelComments [

	^ 'Zmiana modelu Uwagi'
]

{ #category : #translations }
CMPolishTranslator >> tChooseAnotherName [

	^ 'Wybierz inną nazwę'
]

{ #category : #translations }
CMPolishTranslator >> tChooseColor [

	^ 'Wybierz kolor'
]

{ #category : #translations }
CMPolishTranslator >> tChooseDumpDir [

	^ 'Wybierz katalog "Dump":'
]

{ #category : #translations }
CMPolishTranslator >> tChooseStFile [

	^ 'Wybierz plik st'
]

{ #category : #translations }
CMPolishTranslator >> tChooseTokenColor [

	^ 'Wybierz kolor żetonu'
]

{ #category : #translations }
CMPolishTranslator >> tClassifyByParams [

	^ 'Klasyfikacja według parametrów'
]

{ #category : #translations }
CMPolishTranslator >> tClose [

	^ 'Zamknij'
]

{ #category : #translations }
CMPolishTranslator >> tCollectionEmpty [

	^ 'Kolekcja (pusta)'
]

{ #category : #translations }
CMPolishTranslator >> tCommunication [

	^ 'Komunikacja'
]

{ #category : #translations }
CMPolishTranslator >> tConfirmAbstractEntity [

	^ ' jest abstrakcyjna. Zostanie ona zmieniona na klasę konkretną. Ok?'
]

{ #category : #translations }
CMPolishTranslator >> tConfirmBeforeLaunch [

	^ 'Potwierdzenie przed uruchomieniem'
]

{ #category : #translations }
CMPolishTranslator >> tConfirmConcreteEntity [

	^ ' jest konkretna. Zostanie zmieniona na klasę abstrakcyjną. Ok?'
]

{ #category : #translations }
CMPolishTranslator >> tConfirmDeleteAttribute [

	^ 'Czy na pewno chcesz usunąć wybrany atrybut?'
]

{ #category : #translations }
CMPolishTranslator >> tConfirmDeleteEntity [

	^ 'Czy na pewno chcesz usunąć wybraną jednostkę?'
]

{ #category : #translations }
CMPolishTranslator >> tCreateAgent [

	^ 'Stwórz rodzaj agenta'
]

{ #category : #translations }
CMPolishTranslator >> tCreateEntityKind [

	^ 'Tworzenie rodzaju podmiotu'
]

{ #category : #translations }
CMPolishTranslator >> tCreateInstances [

	^ 'Tworzenie wystąpień'
]

{ #category : #translations }
CMPolishTranslator >> tCreatePoVAtt [

	^ 'Utwórz PoV na podstawie którego atrybutu?'
]

{ #category : #translations }
CMPolishTranslator >> tCreationDate [

	^ 'Data utworzenia'
]

{ #category : #translations }
CMPolishTranslator >> tCrossSensAnalysis [

	^ 'Przekrojowa analiza wrażliwości'
]

{ #category : #translations }
CMPolishTranslator >> tCrossedPredefValues [

	^ 'Przekreślone predefiniowane przez listę wartości'
]

{ #category : #translations }
CMPolishTranslator >> tCrossedSeqValues [

	^ 'Przekreślone wartości sekwencyjne'
]

{ #category : #translations }
CMPolishTranslator >> tCurrentStep [

	^ 'bieżący krok'
]

{ #category : #translations }
CMPolishTranslator >> tDefineControl4Scenario [

	^ 'Zdefiniuj co najmniej jedną metodę kontroli w celu przygotowania scenariusza'
]

{ #category : #translations }
CMPolishTranslator >> tDefineEntities [

	^ 'Definiowanie podmiotów'
]

{ #category : #translations }
CMPolishTranslator >> tDefineInit4Scenario [

	^ 'Zdefiniuj co najmniej jedną metodę init do przygotowania scenariusza'
]

{ #category : #translations }
CMPolishTranslator >> tDeveloperTools [

	^ 'Narzędzia deweloperskie'
]

{ #category : #translations }
CMPolishTranslator >> tDisplayLegends [

	^ 'Wyświetlanie legend'
]

{ #category : #translations }
CMPolishTranslator >> tDisplayModelVersions [

	^ 'Wersje modeli z wyświetlaczem'
]

{ #category : #translations }
CMPolishTranslator >> tDisplayParams [

	^ 'Parametry wyświetlania'
]

{ #category : #translations }
CMPolishTranslator >> tDistributeAsClient [

	^ 'Dystrybucja (działanie jako klient)'
]

{ #category : #translations }
CMPolishTranslator >> tDistributeAsServer [

	^ 'Dystrybucja (działanie jako serwer)'
]

{ #category : #translations }
CMPolishTranslator >> tEdit [

	^ 'Edytuj'
]

{ #category : #translations }
CMPolishTranslator >> tEditActivityDiagrams [

	^ 'edytowanie diagramów aktywności'
]

{ #category : #translations }
CMPolishTranslator >> tEditAttributes [

	^ 'edytuj atrybuty'
]

{ #category : #translations }
CMPolishTranslator >> tEditInit [

	^ 'inicjalizacja edycji'
]

{ #category : #translations }
CMPolishTranslator >> tEditSteps [

	^ 'edytuj kroki'
]

{ #category : #translations }
CMPolishTranslator >> tEmail [

	^ 'Email'
]

{ #category : #translations }
CMPolishTranslator >> tEnableStepBack [

	^ 'Włącz cofanie'
]

{ #category : #translations }
CMPolishTranslator >> tEnterAttName [

	^ 'Wprowadź nazwę atrybutu (bez spacji, cyfr i symboli).'
]

{ #category : #translations }
CMPolishTranslator >> tEntities [

	^ 'Podmioty'
]

{ #category : #translations }
CMPolishTranslator >> tExplore [

	^ 'Eksploruj'
]

{ #category : #translations }
CMPolishTranslator >> tFile [

	^ 'Plik'
]

{ #category : #translations }
CMPolishTranslator >> tFillArray [

	^ 'Wypełnienie tablicy wartościami'
]

{ #category : #translations }
CMPolishTranslator >> tFinalStep [

	^ 'ostatni krok'
]

{ #category : #translations }
CMPolishTranslator >> tFinalStepChoice [

	^ 'Ostatni krok:'
]

{ #category : #translations }
CMPolishTranslator >> tFixRandomSeed [

	^ 'Ustal losowe ziarno na'
]

{ #category : #translations }
CMPolishTranslator >> tForwardLabel [

	^ 'Do przodu'
]

{ #category : #translations }
CMPolishTranslator >> tFullNetwork [

	^ 'Pełna sieć'
]

{ #category : #translations }
CMPolishTranslator >> tFullNetworkHelp [

	^ 'Zorientowana sieć składająca się ze zbioru łuków i węzłów'
]

{ #category : #translations }
CMPolishTranslator >> tGetterAccessor [

	^ 'Getter accessor'
]

{ #category : #translations }
CMPolishTranslator >> tGroup [

	^ 'Grupa'
]

{ #category : #translations }
CMPolishTranslator >> tHelp [

	^ 'Pomoc'
]

{ #category : #translations }
CMPolishTranslator >> tHelpAddClassAttr [

	^ 'Dodaje nowy atrybut klasy do klasy docelowej'
]

{ #category : #translations }
CMPolishTranslator >> tHelpAddInstAtt [

	^ 'Dodanie nowego atrybutu do klasy docelowej'
]

{ #category : #translations }
CMPolishTranslator >> tHelpRemoveInstAtt [

	^ 'Usunięcie atrybutu z klasy docelowej'
]

{ #category : #translations }
CMPolishTranslator >> tHowToRunModel [

	^ 'Jak uruchomić ten model'
]

{ #category : #translations }
CMPolishTranslator >> tInitInstantiation [

	^ 'początkowa instancja'
]

{ #category : #translations }
CMPolishTranslator >> tInitialValueChooser [

	^ 'Wybór wartości początkowej'
]

{ #category : #translations }
CMPolishTranslator >> tInitialValueLabel [

	^ 'Wprowadź wartość początkową dla tego atrybutu'
]

{ #category : #translations }
CMPolishTranslator >> tInitialize [

	^ 'Inicjalizacja'
]

{ #category : #translations }
CMPolishTranslator >> tInitializeRandomness [

	^ 'Inicjalizacja losowości'
]

{ #category : #translations }
CMPolishTranslator >> tInspectModel [

	^ 'Sprawdź model'
]

{ #category : #translations }
CMPolishTranslator >> tInvalidName [

	^ ' nie jest prawidłową nazwą. Wprowadź prawidłową nazwę'
]

{ #category : #translations }
CMPolishTranslator >> tLanguage [

	^ 'Język'
]

{ #category : #translations }
CMPolishTranslator >> tLocalImage [

	^ 'Obraz lokalny'
]

{ #category : #translations }
CMPolishTranslator >> tLocalStorage [

	^ 'Dysk lokalny'
]

{ #category : #translations }
CMPolishTranslator >> tLocatedObject [

	^ 'Zlokalizowany obiekt'
]

{ #category : #translations }
CMPolishTranslator >> tLocatedObjectHelp [

	^ 'Jednostka pasywna znajdująca się w komórce'
]

{ #category : #translations }
CMPolishTranslator >> tLocation [

	^ 'Lokalizacja'
]

{ #category : #translations }
CMPolishTranslator >> tManipulateInstances [

	^ 'Manipulowanie instancjami'
]

{ #category : #translations }
CMPolishTranslator >> tMessage [

	^ 'Wiadomość'
]

{ #category : #translations }
CMPolishTranslator >> tMessageHelp [

	^ 'Wiadomość dla AgentCommunication (ze skrzynką pocztową)'
]

{ #category : #translations }
CMPolishTranslator >> tMessages [

	^ 'Wiadomości'
]

{ #category : #translations }
CMPolishTranslator >> tMessagesProgramming [

	^ 'Programowanie wiadomości'
]

{ #category : #translations }
CMPolishTranslator >> tMethods [

	^ 'Metody'
]

{ #category : #translations }
CMPolishTranslator >> tMissingControlMethods [

	^ 'Model nie definiuje żadnej metody kontroli!'
]

{ #category : #translations }
CMPolishTranslator >> tMissingInitMethods [

	^ 'Model nie definiuje żadnej metody inicjalizacji!'
]

{ #category : #translations }
CMPolishTranslator >> tModelComments [

	^ 'Uwagi dotyczące modelu'
]

{ #category : #translations }
CMPolishTranslator >> tModelGlossary [

	^ 'Słowniczek modeli'
]

{ #category : #translations }
CMPolishTranslator >> tModelListing [

	^ 'Lista modeli jako plik tekstowy'
]

{ #category : #translations }
CMPolishTranslator >> tModifiedModelName [

	^ 'Nazwa została zmieniona na'
]

{ #category : #translations }
CMPolishTranslator >> tMonteCarlo [

	^ 'Monte Carlo'
]

{ #category : #translations }
CMPolishTranslator >> tName [

	^ 'Nazwa'
]

{ #category : #translations }
CMPolishTranslator >> tNetworkArc [

	^ 'Network Arc'
]

{ #category : #translations }
CMPolishTranslator >> tNetworkArcHelp [

	^ 'Łuk sieci zlokalizowany w 2 komórkach'
]

{ #category : #translations }
CMPolishTranslator >> tNetworkNode [

	^ 'Węzeł sieci'
]

{ #category : #translations }
CMPolishTranslator >> tNetworkNodeHelp [

	^ 'Węzeł sieci znajdujący się w komórce'
]

{ #category : #translations }
CMPolishTranslator >> tNew [

	^ 'Nowość'
]

{ #category : #translations }
CMPolishTranslator >> tNewEntity [

	^ 'Nowy podmiot'
]

{ #category : #translations }
CMPolishTranslator >> tNewProjectInvalidName [

	^ 'Nazwa projektu jest nieprawidłowa. Spróbuj ponownie'
]

{ #category : #translations }
CMPolishTranslator >> tNewProjectName [

	^ 'Nowa nazwa projektu'
]

{ #category : #translations }
CMPolishTranslator >> tNoStoredSim [

	^ 'Katalog "Dump" nie zawiera zapisanych symulacji'
]

{ #category : #translations }
CMPolishTranslator >> tNoStoredSimFolder [

	^ ' katalog nie zawiera zapisanych symulacji'
]

{ #category : #translations }
CMPolishTranslator >> tNoValue [

	^ 'Brak wartości lub inna instancja (do wysłania w #init)'
]

{ #category : #translations }
CMPolishTranslator >> tNoVersion [

	^ 'Brak wersji'
]

{ #category : #translations }
CMPolishTranslator >> tNotifyObs [

	^ 'Powiadamianie obserwatorów o zmianach'
]

{ #category : #translations }
CMPolishTranslator >> tNumber [

	^ 'Liczba'
]

{ #category : #translations }
CMPolishTranslator >> tNumberOfEntities [

	^ 'Liczba podmiotów'
]

{ #category : #translations }
CMPolishTranslator >> tOATPredefValues [

	^ 'Predefiniowane przez listę wartości'
]

{ #category : #translations }
CMPolishTranslator >> tOATSensAnalysis [

	^ 'Analiza wrażliwości OAT'
]

{ #category : #translations }
CMPolishTranslator >> tOATSeqValues [

	^ 'Wartości sekwencyjne'
]

{ #category : #translations }
CMPolishTranslator >> tObject [

	^ 'Obiekt'
]

{ #category : #translations }
CMPolishTranslator >> tObjectHelp [

	^ 'Prosta jednostka pasywna'
]

{ #category : #translations }
CMPolishTranslator >> tObserver [

	^ 'Obserwator...'
]

{ #category : #translations }
CMPolishTranslator >> tOk [

	^ 'Ok'
]

{ #category : #translations }
CMPolishTranslator >> tOpen [

	^ 'Otwarty'
]

{ #category : #translations }
CMPolishTranslator >> tOpenCormasIssue [

	^ 'Otwórz sprawę'
]

{ #category : #translations }
CMPolishTranslator >> tOpenPharoMenu [

	^ 'Otwórz menu Pharo'
]

{ #category : #translations }
CMPolishTranslator >> tOpenSystemBrowser [

	^ 'Otwórz przeglądarkę systemową'
]

{ #category : #translations }
CMPolishTranslator >> tPackageDepedenciesGraph [

	^ 'Otwarty wykres zależności pakietów'
]

{ #category : #translations }
CMPolishTranslator >> tPackageDepedenciesTool [

	^ 'Open Package Dependencies Analyzer'
]

{ #category : #translations }
CMPolishTranslator >> tPassive [

	^ 'Pasywny'
]

{ #category : #translations }
CMPolishTranslator >> tPhoto [

	^ 'Zdjęcie'
]

{ #category : #translations }
CMPolishTranslator >> tPoV [

	^ 'PoV'
]

{ #category : #translations }
CMPolishTranslator >> tPoVDefinition [

	^ 'Definicja PoV'
]

{ #category : #translations }
CMPolishTranslator >> tPoVInfoDisplayed [

	^ 'Informacje do wyświetlenia'
]

{ #category : #translations }
CMPolishTranslator >> tPoVListInfo [

	^ 'Metody zwracające ciąg znaków'
]

{ #category : #translations }
CMPolishTranslator >> tPoVListMethods [

	^ 'Metody zwracające kolor lub symbol'
]

{ #category : #translations }
CMPolishTranslator >> tPoVListSymbols [

	^ 'Powiązane symbole'
]

{ #category : #translations }
CMPolishTranslator >> tPoVSetColor [

	^ 'Ustaw kolor'
]

{ #category : #translations }
CMPolishTranslator >> tPoVSetter [

	^ 'PoV Setter'
]

{ #category : #translations }
CMPolishTranslator >> tProbes [

	^ 'Sondy'
]

{ #category : #translations }
CMPolishTranslator >> tProbesProgramming [

	^ 'Ustawiacz sond'
]

{ #category : #translations }
CMPolishTranslator >> tProgramming [

	^ 'Programowanie'
]

{ #category : #translations }
CMPolishTranslator >> tProgrammingEntityClass [

	^ 'klasa dla każdego podmiotu...'
]

{ #category : #translations }
CMPolishTranslator >> tProjectOpenFailed [

	^ 'Projekt nie został otwarty, spróbuj ponownie'
]

{ #category : #translations }
CMPolishTranslator >> tProperties [

	^ 'Właściwości'
]

{ #category : #translations }
CMPolishTranslator >> tQuerySaveProject [

	^ 'Projekt został zmieniony, czy chcesz go zapisać?'
]

{ #category : #translations }
CMPolishTranslator >> tQuit [

	^ 'Odejdź'
]

{ #category : #translations }
CMPolishTranslator >> tRandom [

	^ 'Losowo'
]

{ #category : #translations }
CMPolishTranslator >> tReleaseRandomSeed [

	^ 'Zwolnienie losowego ziarna po inicjalizacji'
]

{ #category : #translations }
CMPolishTranslator >> tRemoteImage [

	^ 'Zdalny obraz'
]

{ #category : #translations }
CMPolishTranslator >> tRemove [

	^ 'Usunąć'
]

{ #category : #translations }
CMPolishTranslator >> tRename [

	^ 'Zmiana nazwy'
]

{ #category : #translations }
CMPolishTranslator >> tRenameEntityDialogText [

	^ 'Wprowadź nazwę podmiotu:'
]

{ #category : #translations }
CMPolishTranslator >> tReplay [

	^ 'powtórka'
]

{ #category : #translations }
CMPolishTranslator >> tReplayStartStep [

	^ 'Powtórka rozpocznie się od kroku'
]

{ #category : #translations }
CMPolishTranslator >> tRunCormasTests [

	^ 'Uruchom testy CORMAS'
]

{ #category : #translations }
CMPolishTranslator >> tSave [

	^ 'Zapisz'
]

{ #category : #translations }
CMPolishTranslator >> tSaveAs [

	^ 'Zapisz jako'
]

{ #category : #translations }
CMPolishTranslator >> tScheduler [

	^ 'harmonogram'
]

{ #category : #translations }
CMPolishTranslator >> tSelectControlMethod [

	^ 'Wybór metody kontroli'
]

{ #category : #translations }
CMPolishTranslator >> tSelectInitMethod [

	^ 'Wybierz metodę inicjalizacji'
]

{ #category : #translations }
CMPolishTranslator >> tSelectMethod [

	^ 'Wybierz metodę'
]

{ #category : #translations }
CMPolishTranslator >> tSelectProbesToRecord [

	^ 'Wybór sond do nagrywania'
]

{ #category : #translations }
CMPolishTranslator >> tSetterAccessor [

	^ 'Setter accessor'
]

{ #category : #translations }
CMPolishTranslator >> tSimCloseHelp [

	^ 'Zamknij interfejs symulacji'
]

{ #category : #translations }
CMPolishTranslator >> tSimFinalStepHelp [

	^ 'Przejdź do ostatniego kroku'
]

{ #category : #translations }
CMPolishTranslator >> tSimInformation [

	^ 'Informacje o symulacji'
]

{ #category : #translations }
CMPolishTranslator >> tSimInterface [

	^ 'Interfejs symulacji'
]

{ #category : #translations }
CMPolishTranslator >> tSimOrganization [

	^ 'symulacja Organizacja...'
]

{ #category : #translations }
CMPolishTranslator >> tSimStepHelp [

	^ 'Aktualny czas'
]

{ #category : #translations }
CMPolishTranslator >> tSimpleCell [

	^ 'Simple Cell'
]

{ #category : #translations }
CMPolishTranslator >> tSimpleCellHelp [

	^ 'SpatialEntityElement jest podstawową jednostką Cell'
]

{ #category : #translations }
CMPolishTranslator >> tSimpleStochAnalysis [

	^ 'Prosta analiza stochastyczna'
]

{ #category : #translations }
CMPolishTranslator >> tSimulate [

	^ 'symulować'
]

{ #category : #translations }
CMPolishTranslator >> tSimulation [

	^ 'Symulacja'
]

{ #category : #translations }
CMPolishTranslator >> tSnapshot [

	^ 'Migawka bieżącego stanu'
]

{ #category : #translations }
CMPolishTranslator >> tSocial [

	^ 'Społeczny'
]

{ #category : #translations }
CMPolishTranslator >> tSpace [

	^ 'Przestrzeń'
]

{ #category : #translations }
CMPolishTranslator >> tSpaceEntities [

	^ 'Przestrzeń i byty'
]

{ #category : #translations }
CMPolishTranslator >> tSpaceInterface [

	^ 'Interfejs kosmiczny'
]

{ #category : #translations }
CMPolishTranslator >> tSpatial [

	^ 'Przestrzenny'
]

{ #category : #translations }
CMPolishTranslator >> tSpecialization [

	^ 'Specjalizacja'
]

{ #category : #translations }
CMPolishTranslator >> tSpecialize [

	^ 'Specjalizować się'
]

{ #category : #translations }
CMPolishTranslator >> tSpecializeEntityDialogText [

	^ 'Utwórz nowy rodzaj podmiotu: Wprowadź nazwę podmiotu'
]

{ #category : #translations }
CMPolishTranslator >> tStFiles [

	^ 'pliki st'
]

{ #category : #translations }
CMPolishTranslator >> tStartRWebService [

	^ 'Uruchom usługę sieci Web dla R'
]

{ #category : #translations }
CMPolishTranslator >> tStopRWebService [

	^ 'Stop Web Service for R'
]

{ #category : #translations }
CMPolishTranslator >> tStringSymbol [

	^ 'String / Symbol'
]

{ #category : #translations }
CMPolishTranslator >> tTools [

	^ 'Narzędzia'
]

{ #category : #translations }
CMPolishTranslator >> tUsefulExpressions [

	^ 'Przydatne wyrażenia'
]

{ #category : #translations }
CMPolishTranslator >> tValidNameRequired [

	^ 'Podaj prawidłową nazwę'
]

{ #category : #translations }
CMPolishTranslator >> tVersionName [

	^ 'Nazwa wersji'
]

{ #category : #translations }
CMPolishTranslator >> tVideo [

	^ 'Wideo'
]

{ #category : #translations }
CMPolishTranslator >> tVisualization [

	^ 'Wizualizacja'
]

{ #category : #translations }
CMPolishTranslator >> tWhichModel [

	^ 'Który model?'
]

{ #category : #translations }
CMPolishTranslator >> tWhichOpeningLocation [

	^ 'Wybierz otwartą lokalizację'
]
