error handling
remoteSelectors
	
	^#(#absoluteBounds #gridCellShape #nbNeighbours #timeUnitName #envSpecStringFor: #boundaries #spatialClasses #cormasModel #spatialEntities #cormas #testSpatialEntitiesAt:povAt: #spatialEntitiesAt: #allTheEntities: #allTheSituatedEntities: #spatialEntitiesAt:withPovResultFor: #getPovsDataOfEntity:forSelector:andInfo: #getPovsDataOfOccupantEntity:forSelector:andInfo: #elementaryEntities)