Class {
	#name : 'CMCat',
	#superclass : 'Object',
	#classVars : [
		'icons'
	],
	#category : 'Cormas-UI-Tilesets',
	#package : 'Cormas-UI-Tilesets'
}

{ #category : 'accessing - icons' }
CMCat class >> frame00 [
	"Private - Generated method"
	<script: 'self frame00 inspect'>
	^ self icons
		at: #frame00
		ifAbsentPut: [ Form fromBinaryStream: self frame00Contents base64Decoded asByteArray readStream ]
]

{ #category : 'private - contents' }
CMCat class >> frame00Contents [
	"Private - Method generated with the content of the file File @ /Users/zaitsev/Downloads/Basic Charakter Spritesheet/00_Basic Charakter Spritesheet.png"
	^ 'iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAABXAvmHAAAAAXNSR0IArs4c6QAAAZdJREFUaENjZBjigHGIu59h1AMDHYOjMTAaAxSGwGgSojAAKdY+GgMUByGFBozGAIUBSLH20RigOAgpNGA0BpADMMZv0n8Yf8mmPJTAwSdHSSRQLQZADpy+RA/ulsyYSwwwT+CTo8TxIL1U9UBPuhTYPdy2IgwgDyADkOe+Hn4DFiqZ+QzuuUHrgVeP5VDcJib7aPB7ADkJYfMAzEfIyWtQxcCQ9QCshEH2AL6QheUP9JKKnNigaiYGeQDkOFwegckNuiQ0fGKgyxiSCqR+Y08Nz1jB4pllZwdfMQpyGCwmpOQlsHrg2cMXYHFqpH2YBVTNA43tPgyg8r65+hWkwio5x8Ap6AHn17aKMYCK1/rKLVTzBE08AAud7+93gJkgT8DAoPUAchLCVwoN2iQEC2FQPgAlJRAAJRUQQOZTM/2DzKZaEkLOtbDMjNwapXbIUz0Tk1OLUkMPTWKAGg4j1oxRDxAbUrRSNxoDtApZYs0djQFiQ4pW6kZjgFYhS6y5ozFAbEjRSt1oDNAqZIk1dzQGiA0pWqkDAG7ypjGA8mmUAAAAAElFTkSuQmCC'
]

{ #category : 'accessing - icons' }
CMCat class >> frame01 [
	"Private - Generated method"
	<script: 'self frame01 inspect'>
	^ self icons
		at: #frame01
		ifAbsentPut: [ Form fromBinaryStream: self frame01Contents base64Decoded asByteArray readStream ]
]

{ #category : 'private - contents' }
CMCat class >> frame01Contents [
	"Private - Method generated with the content of the file File @ /Users/zaitsev/Downloads/Basic Charakter Spritesheet/01_Basic Charakter Spritesheet.png"
	^ 'iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAABXAvmHAAAAAXNSR0IArs4c6QAAAZVJREFUaEPtV71KA0EQ3hQWYiWIyIH6Bmms7S0kT5Be0lgdgliIWAhiZSP2eQJJYW+thW+gwiFBsBILC2U2jIzrxsLvO3IHs81xu7ez38/MbNIJLR+dluMPTmDWDroD7gCogKcQKCC83R2AJQQDuAOggPB2dwCWEAzgDqiA/d75pxVzeLX7Sxz7TW79P2ZQHBBgF8Pu9/mD/n0WS/oNgwSNwNlOEUEvbC7F5/hp7QeJ5dXH+P528xKf5WUVnEAIvH9kaRpNc0DUlxRjqC+xaCkkwWyO/1WQWiMMEhQCAlYdEHDTiOiaO2Ds5TpwujEJXXzkM6iai/ODvdtm1UB6mRXrK1kC1cNznGfkvh5Ac8CSUAJleRfmF7fC8cE4LgsBJnhaF7Lgj062g15a76/XcUlI6OV2uD+ikqA6IJ3IEkjzSO6GRhOw7TRXBMz2WWsNiAsyRG0Z9r3RNZB2IwWrP6PZ4OlFnG/+9c5Si7heqPnoTmAWqtsz3QF3AFTAUwgUEN7uDsASggHcAVBAeLs7AEsIBmi9A19AEZwxeVRTTAAAAABJRU5ErkJggg=='
]

{ #category : 'accessing - icons' }
CMCat class >> frame02 [
	"Private - Generated method"
	<script: 'self frame02 inspect'>
	^ self icons
		at: #frame02
		ifAbsentPut: [ Form fromBinaryStream: self frame02Contents base64Decoded asByteArray readStream ]
]

{ #category : 'private - contents' }
CMCat class >> frame02Contents [
	"Private - Method generated with the content of the file File @ /Users/zaitsev/Downloads/Basic Charakter Spritesheet/02_Basic Charakter Spritesheet.png"
	^ 'iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAABXAvmHAAAAAXNSR0IArs4c6QAAAYdJREFUaENjZBjigHGIu59h1AMDHYOjMTAaAxSGwGgSojAAKdY+GgMUByGFBozGAIUBSLH20RigOAgpNGA0BpADMMZv0n8Yf8mmPJTAwSdHSSRQLQZADpy+RA/ulsyYSwwwT+CTo8TxIL1U9UBPuhTYPdy2IgwgDyADkOe+Hn4DFiqZ+QzuuUHrgVeP5VDcJib7aPB7ADkJYfMAzEfIyWtQxcCQ9QCshEH2AL6QheUP9JKKnNigaiYGeQDkOFwegckNuiQ0fGKgyxiSCqR+Y08Nz1jB4pllZwdnMQpztZS8BFYPPHv4AixOjbQPs4CqeaCx3YcBVN43V7+CVFgl5xg4BT3g/EHtAZCD0ZsM39/vAHsE5AkYANUP9ZVbqBYLVIsBmAPRPYFceYFKpyHhAVBSAgFQSOMC1MoHVI8BWFKidmbFFRA08QA5NSq5ekY9QG7IUUvfaAxQKyTJNWc0BsgNOWrpG40BaoUkueaMxgC5IUctfaMxQK2QJNec0RggN+SopW/IxwAALKOhMeBoD+MAAAAASUVORK5CYII='
]

{ #category : 'accessing - icons' }
CMCat class >> frame03 [
	"Private - Generated method"
	<script: 'self frame03 inspect'>
	^ self icons
		at: #frame03
		ifAbsentPut: [ Form fromBinaryStream: self frame03Contents base64Decoded asByteArray readStream ]
]

{ #category : 'private - contents' }
CMCat class >> frame03Contents [
	"Private - Method generated with the content of the file File @ /Users/zaitsev/Downloads/Basic Charakter Spritesheet/03_Basic Charakter Spritesheet.png"
	^ 'iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAABXAvmHAAAAAXNSR0IArs4c6QAAAYxJREFUaEPtlbFKA0EQhjeFhVgJEuRAfQMba/sU4hOklzSpDkEkiIgIkipNsM8TiIW9tRa+QRI4JAhWYpFCmZU5NnJ3Rf5f3JPZKtll5ub/v9nZhqv5atS8fmcC/pqgETACoAPWQqCBcLgRgC0EExgB0EA43AjAFoIJjEBoYPtw8Kn/R7fdBXOqzhAINAJS4HC0m9fSaT87FVF1hhQvsVQB/aPE17O2v+FEQLhE3PvDq99Kb7JcXLQCZtPthdqaW5P4BYQtVCRAFYXtFRWB2grQCRMKqHJW78fPSbUMDeolFgFSXJkQPYuuhf4Pgeu97y5I5sXdkK34/c7xY3xjVApTEsnOZqGAbPyS7zP6n/qQFQlI0ye3ut5yF6czX3jvsulkvJ6d3MVHQNw/vzpw8mDp+ni79z9FxG+8AVQCoYCyScScPmoIdYyWzXEhI4vZOnQBVY+QXm7WxQ2/RSOwzCvKiDEBDBeRHEYAcY8RawQYLiI5jADiHiPWCDBcRHIYAcQ9RqwRYLiI5Kg9gS+yH50xSHQpTwAAAABJRU5ErkJggg=='
]

{ #category : 'accessing - icons' }
CMCat class >> frame04 [
	"Private - Generated method"
	<script: 'self frame04 inspect'>
	^ self icons
		at: #frame04
		ifAbsentPut: [ Form fromBinaryStream: self frame04Contents base64Decoded asByteArray readStream ]
]

{ #category : 'private - contents' }
CMCat class >> frame04Contents [
	"Private - Method generated with the content of the file File @ /Users/zaitsev/Downloads/Basic Charakter Spritesheet/04_Basic Charakter Spritesheet.png"
	^ 'iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAABXAvmHAAAAAXNSR0IArs4c6QAAAVBJREFUaEPtVl0KAVEUvjYhKezASmQFNuDFuyRJ8u7FBqxAVmIHKGk2QUeO7mgM+T6ZqW+eXLdzfH/njEoo+VMpOf4gAv92UA7IAVABRQgUEC6XA7CEYAM5AAoIl8sBWEKwgRyIBex1lxc/rzeDlDh5d4gJNAcM4GrdfmDp93bBSeTdIeCt9qcEYnCvyBWWQHJsprBVG4dMdwpLIA9YHC8RQBWwet8wcc7fOWD3z5vqGyw/G+J3BBjgaVtIDnyTnXsNLULxLNRbtUxIp/359j0rPrQIOfjpohNs389GyQ2oA3ZC43k12PthMtzSSNAcsDlwAgbedr1vpfhzYQl8sk6NSGEj5KF3J+xsUbHHnPEzM//UGYin1tdq/G+Urbz/Hm0GgE0IlYoAJB+hWA4QRIRayAFIPkKxHCCICLWQA5B8hGI5QBARaiEHIPkIxaV34ApVE5Qx6G2kfgAAAABJRU5ErkJggg=='
]

{ #category : 'accessing - icons' }
CMCat class >> frame05 [
	"Private - Generated method"
	<script: 'self frame05 inspect'>
	^ self icons
		at: #frame05
		ifAbsentPut: [ Form fromBinaryStream: self frame05Contents base64Decoded asByteArray readStream ]
]

{ #category : 'private - contents' }
CMCat class >> frame05Contents [
	"Private - Method generated with the content of the file File @ /Users/zaitsev/Downloads/Basic Charakter Spritesheet/05_Basic Charakter Spritesheet.png"
	^ 'iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAABXAvmHAAAAAXNSR0IArs4c6QAAAUtJREFUaEPtVssJwkAQTZoQEdQOrESsIA148e5JPHn3YgOpQKzEDlQQsQllhJHNGhKYecENvD0ZNzP7PjM7ybOer7zn+DMS+LeDdIAOOBVgCTkFdIfTAbeEzgR0wCmgO5wOuCV0JqADKmCx2L9CMcvj6kec8J26fYsZEAcE2KGcfc9fFudaLPE7CBKdEBD0z9ukQmIwvlaehWTSBNrKISkCAjYuoyYCKPByBqyEJFlY420EZD+ZEqIDbQ3TsA8pod47EA+z0XRYq9n98vj8j6h9PQDmQEiiiQASPOwWCsFvd/NMh5ZOZL2dZLht1qd0HZBZoAQEvALX38kTaGtm5ADrtAfEBVlSLrLC56R7IL6NFKx+RqPBw5vYMY/MofBr1IzEGEgCRuFgYXQAJqUxER0wCgcLowMwKY2J6IBROFgYHYBJaUxEB4zCwcLeX4KKMbzKZHIAAAAASUVORK5CYII='
]

{ #category : 'accessing - icons' }
CMCat class >> frame06 [
	"Private - Generated method"
	<script: 'self frame06 inspect'>
	^ self icons
		at: #frame06
		ifAbsentPut: [ Form fromBinaryStream: self frame06Contents base64Decoded asByteArray readStream ]
]

{ #category : 'private - contents' }
CMCat class >> frame06Contents [
	"Private - Method generated with the content of the file File @ /Users/zaitsev/Downloads/Basic Charakter Spritesheet/06_Basic Charakter Spritesheet.png"
	^ 'iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAABXAvmHAAAAAXNSR0IArs4c6QAAAVNJREFUaEPtVssJwkAQ3TQhIqgdWIlYQRrw4t2DiAfx7sUGUoFYiR2oIGITyoITJiFulsyMJvByMu7u+H4za+I6/iQdx+9A4N8OwgE4IFQAERIKKD4OB8QSCgvAAaGA4uNwQCyhsAAc4AKms/2L3rPjoiBOaE1igpoDHuAhm+RY5unZEYnQmgS8P2tKgIP7Rq61BJ63UQFbb3itdKe1BELAeLxAQKqAP08Thue8zgG/Xp5UTbCYNXEdAQ3walMIDjTJzueMWoR4LwzG/UpI98sj/75VESJUFCUiQIDpfbXtOX8/rJcnlQZW6wFSf7ObOrqw/KynqVT+rKW+GQEOmGdJ8wKjumo9wP9tlhvAO+MfzeioEwgNEiKnGZ2fEhBMydqjahGq/SWjDSBgJGx0WTgQLZXRRjhgJGx0WTgQLZXRRjhgJGx0WTgQLZXRRjhgJGx02TeYQIsxRLv+rgAAAABJRU5ErkJggg=='
]

{ #category : 'accessing - icons' }
CMCat class >> frame07 [
	"Private - Generated method"
	<script: 'self frame07 inspect'>
	^ self icons
		at: #frame07
		ifAbsentPut: [ Form fromBinaryStream: self frame07Contents base64Decoded asByteArray readStream ]
]

{ #category : 'private - contents' }
CMCat class >> frame07Contents [
	"Private - Method generated with the content of the file File @ /Users/zaitsev/Downloads/Basic Charakter Spritesheet/07_Basic Charakter Spritesheet.png"
	^ 'iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAABXAvmHAAAAAXNSR0IArs4c6QAAAUpJREFUaEPtls0JwkAQhZMmRAS1AysRK0gDXryLBxEP3r3YQCoQK7EDFUTShDLBkU3ID5t5wQTenjTLLO+9b3aSMOj5CnuuP6CBfxMkARIwJsAWMgZoLicBc4TGA0jAGKC5nATMERoPIAE3wGhxfOv/+LzKhFO1Z4EAIyACT/Hsp2UZXQM1UbVnES+1rRpwxZWZ66yB5DHJaBuM74V0OmugSpjbXjRgTUDqdcK4fV5HQPbzk6qJltYucZ0BhHjYFCKBJr3zrYG2kOoYTYeFkp63V/oc1T6wFtKLvDvMA5n3+02SClXBaqjTBtSETiKZ9UW/5QW3XV9gFGAtpD2T/+7R52qoFwaklWRJ0mULdQ/gBNwXG0pk1ZBqxYBhKnqX0oB3ZOACEgAH6n0cCXhHBi4gAXCg3seRgHdk4AISAAfqfRwJeEcGLug9gQ8SxI8xXgi5fwAAAABJRU5ErkJggg=='
]

{ #category : 'accessing - icons' }
CMCat class >> frame08 [
	"Private - Generated method"
	<script: 'self frame08 inspect'>
	^ self icons
		at: #frame08
		ifAbsentPut: [ Form fromBinaryStream: self frame08Contents base64Decoded asByteArray readStream ]
]

{ #category : 'private - contents' }
CMCat class >> frame08Contents [
	"Private - Method generated with the content of the file File @ /Users/zaitsev/Downloads/Basic Charakter Spritesheet/08_Basic Charakter Spritesheet.png"
	^ 'iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAABXAvmHAAAAAXNSR0IArs4c6QAAAVpJREFUaENjZBjigHGIu59h1AMDHYOjMTAaAxSGwGgSojAAKdY+GgMUByGFBozGAIUBSLH20RigOAgpNGA0BvAFYIzfpP8w+SWb8mgSWDQxFORokOOnL9GD+y8z5hIDLTxBEw/AQh7kga+H34A9wW0rwkALT1DdA+ghP+Q9gJxHhmQMDCkPIKd9bKUTKAZAgJqZmap5ADn9gxyLXAqBHD7okxB6BkaPhSEVA2DHP2OF+EHqN5ga9DEAq8Ck5CUwssCzhy+omvZhFlA1D4AMffWw4n9PjxGKB2pbxRhePZZjqK/cQnVP0MQDRblSGBl4yHgAWzuIVukfZC7VYwCWdkAlUmO7D5hLi6RDszyAnPhhFRs1Ky700oFmMYCtJqaF2KgHaBGqpJg5GgOkhBYt1I7GAC1ClRQzR2OAlNCihdrRGKBFqJJi5mgMkBJatFA7GgO0CFVSzBzyMQAAo3Z9MShVb1MAAAAASUVORK5CYII='
]

{ #category : 'accessing - icons' }
CMCat class >> frame09 [
	"Private - Generated method"
	<script: 'self frame09 inspect'>
	^ self icons
		at: #frame09
		ifAbsentPut: [ Form fromBinaryStream: self frame09Contents base64Decoded asByteArray readStream ]
]

{ #category : 'private - contents' }
CMCat class >> frame09Contents [
	"Private - Method generated with the content of the file File @ /Users/zaitsev/Downloads/Basic Charakter Spritesheet/09_Basic Charakter Spritesheet.png"
	^ 'iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAABXAvmHAAAAAXNSR0IArs4c6QAAAV5JREFUaEPtlTEKwlAMhl8HJ1cR6aA3cHD3BuIJegEHHZx0EHEQl04uXqAnEG/gDbxBEYqIq5ODkkqktpU3JFEfpEtLSdP8/5e8eMbxy3O8fqMCfk1QCSgBogPaQkQDyZ8rAbKFxARKgGgg+XMlQLaQmEAJ2AwM+us7xkTbEbth7Amh2GzRm6j90jgIDoZbBLsAKD5bNFR/3V9SEdVuzXCLUAH5GSgjgDHc7kNeVgLY+/kWygqAZ845YBeAxYPbeSFOEPjkPjgPApwhkFaaVJ7d49/S298TwB3gtxqF/ZbEJ9bexx+wzgAkPceTexh23gTMlnVzPjbNfLpjFyEiYDz0CwPsjABso2+cQOx7APumbJlJDLCYAKSwWPVSTRK9LzbE2enFzcy5efPHG/sQF85P4RcqQNhga3olYLVIOEAJCBtsTa8ErBYJBygBYYOt6ZWA1SLhACUgbLA1vfMEHjcYfTF7EswtAAAAAElFTkSuQmCC'
]

{ #category : 'accessing - icons' }
CMCat class >> frame10 [
	"Private - Generated method"
	<script: 'self frame10 inspect'>
	^ self icons
		at: #frame10
		ifAbsentPut: [ Form fromBinaryStream: self frame10Contents base64Decoded asByteArray readStream ]
]

{ #category : 'private - contents' }
CMCat class >> frame10Contents [
	"Private - Method generated with the content of the file File @ /Users/zaitsev/Downloads/Basic Charakter Spritesheet/10_Basic Charakter Spritesheet.png"
	^ 'iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAABXAvmHAAAAAXNSR0IArs4c6QAAAVlJREFUaEPtlTEKwkAQRdfCylZEUugNLOy9gXgCL2ChhZUWIhZik8rGC+QE4g28gTcQIUiwtbJQJrKyJkEWZj9mYbYRzGYy/7/5uxXl+ap43r8SAf8mKASEANMBGSGmgezXhQDbQmYBIcA0kP26EGBbyCwgBH4ZOBxsn/p5tJ9AzIIUpaap+V3U+egbDU8KIQIiQDtPAu7HWyqi1qsrhAjnArLOey/AzIiXBLwSYM5+0elEBGi5DLPTDJjzT82apxA1XvoRygY4S8ErAmnzcfWtIXikP6UnoC+woN3MRSA+X53Ovv6A0wxQ0eQ8e4Zh90vAYt1QyaWllvODcxEQAdNxkAuwNwKKgowIL2yESMBq00/r08iYy+X5DxOgg6wvLH25IZqnbzjPQNENjPxPBCDdtaktBGxcQu4RAkh3bWoLARuXkHuEANJdm9pCwMYl5B4hgHTXprb3BF6p7IExXhG8XwAAAABJRU5ErkJggg=='
]

{ #category : 'accessing - icons' }
CMCat class >> frame11 [
	"Private - Generated method"
	<script: 'self frame11 inspect'>
	^ self icons
		at: #frame11
		ifAbsentPut: [ Form fromBinaryStream: self frame11Contents base64Decoded asByteArray readStream ]
]

{ #category : 'private - contents' }
CMCat class >> frame11Contents [
	"Private - Method generated with the content of the file File @ /Users/zaitsev/Downloads/Basic Charakter Spritesheet/11_Basic Charakter Spritesheet.png"
	^ 'iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAABXAvmHAAAAAXNSR0IArs4c6QAAAVFJREFUaEPtlTEKwkAQRTeFla2IBMQbWNh7A/EEuYCFFlZaiZVNKhsv4AnEG3gDbxCLIGJrZRGZyMqyBpu/ow7MNoGEncz/b/5uZISvSHj/RgX8mqASUAKgAzpCoIHwdiUAWwgWUAKggfB2JQBbCBZQAp8MTIbrwn7f7iYsZrEUpaap+c22+9I3So6GQwSLAOs8CbgdrqWIer9hOEQEF+A7L16AmxGRBEQJcGe/6nQiArRChjloBtz5p2bdU4ga//sR8gPsUxBFoGw+rz01xPfy8fcE7AUWd1pvEcizc9DZtz8ImgEqeslmRZr2DDW8XA1Ms31ic58KswiYjuOyaZEC3KPUP4nEZMAPAJGgtZjvg+cg+AjZILsXlqUS8gJjC3HVDcz5joUAZ8N+bRXwTber/qUElADogI4QaCC8XQnAFoIFlABoILxdCcAWggXEE3gAquKFMd0tHuQAAAAASUVORK5CYII='
]

{ #category : 'accessing - icons' }
CMCat class >> frame12 [
	"Private - Generated method"
	<script: 'self frame12 inspect'>
	^ self icons
		at: #frame12
		ifAbsentPut: [ Form fromBinaryStream: self frame12Contents base64Decoded asByteArray readStream ]
]

{ #category : 'private - contents' }
CMCat class >> frame12Contents [
	"Private - Method generated with the content of the file File @ /Users/zaitsev/Downloads/Basic Charakter Spritesheet/12_Basic Charakter Spritesheet.png"
	^ 'iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAABXAvmHAAAAAXNSR0IArs4c6QAAAVhJREFUaEPtlz0OAVEUhZ9CpRWRScQO7MAOxApsQKPSiEJEQaWgsAErEDvQK+yAYiKiVSnII1f8DcU5d5jkTmfk3bnf+e57Q8ol/EolvH9nAL82aAbMAJiAjRAYILzcDMARggXMABggvNwMwBGCBcxAVIC16ugk301nDbWgVAr75ifT0o2tXls5LQg6gDR/WOwvAJly1nkAf2lAxAIgKjRMqAG82xsG8CYVqgE5ee438P0zNfYCFcA3+3wC+Xu+cYFijxEV4JsBgWGeRlSAFwNh+jpBwVHtnUAHEIigmH/ZcuF6S38X0AH8GHX7FZcrbFyvvXuAaDaXLlccUJ9JLSbpC8DzCTQch/8P8OkkYm5eCYduQArLKPnPndacPvvqAGJC60dcLABR/xWY99VGiNnkp1oGEFfSUc8xA2YATMBGCAwQXm4G4AjBAmYADBBebgbgCMECiTdwBnHyeTECrGCBAAAAAElFTkSuQmCC'
]

{ #category : 'accessing - icons' }
CMCat class >> frame13 [
	"Private - Generated method"
	<script: 'self frame13 inspect'>
	^ self icons
		at: #frame13
		ifAbsentPut: [ Form fromBinaryStream: self frame13Contents base64Decoded asByteArray readStream ]
]

{ #category : 'private - contents' }
CMCat class >> frame13Contents [
	"Private - Method generated with the content of the file File @ /Users/zaitsev/Downloads/Basic Charakter Spritesheet/13_Basic Charakter Spritesheet.png"
	^ 'iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAABXAvmHAAAAAXNSR0IArs4c6QAAAVhJREFUaEPtlT8OAVEQxp9CpRWRTWRv4AZuIE7gAhrVNqIQUVApKFzACcQN9Ao3oNiIaFUKMmRk9+3SfPPYldlq/+TNm+/7fW+2YHJ+FXLev1EBvyaoBJQA6IBGCDQQXq4EYAvBAkoANBBergRgC8ECSiDNwHZrduP3y1XXqUnixan5xbL+0tVp7173LsSICuDmL5vzo+lSoxwDRGKkRagA+wzYEYp+zwUBajh6BmwB9CwZI9EIUXNpBMh5FiVNQVQAj893BEhgpgUkCITFZ4K8a2ysZjpCLMLzq4l/XLg/iuafNhCNEDc/HDdNpXYwo/4pJiIItqbiT0T3FC1mC7An0HQeZl/Ap0kkmX02R5zAXwiIRonuB721+OF1SoCL83/BRXS+IiAxRx28cHIGHPT5tqQK+KbbaXspASUAOqARAg2ElysB2EKwgBIADYSXKwHYQrBA7gncAXlneTFF0ec+AAAAAElFTkSuQmCC'
]

{ #category : 'accessing - icons' }
CMCat class >> frame14 [
	"Private - Generated method"
	<script: 'self frame14 inspect'>
	^ self icons
		at: #frame14
		ifAbsentPut: [ Form fromBinaryStream: self frame14Contents base64Decoded asByteArray readStream ]
]

{ #category : 'private - contents' }
CMCat class >> frame14Contents [
	"Private - Method generated with the content of the file File @ /Users/zaitsev/Downloads/Basic Charakter Spritesheet/14_Basic Charakter Spritesheet.png"
	^ 'iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAABXAvmHAAAAAXNSR0IArs4c6QAAAWhJREFUaEPtljFqAlEQhp9FKtsgQRBvkBvkBsETeAEbKxuxkGChVYqkyAU8QfAG9ilyA1MsQWytLAyjjGxWJTDzj3Hh30ZZmbfz/d97s1ZSya9KyftPBPhvgzRAA84EuIWcAbrLacAdoXMBGnAG6C6nAXeEzgVo4FyA7dbLVn+bvnfDggpZWJp/m94f2DrtzxQFAQfQ5tfz1Q6g+nCbBECuCIiLAKiKCBNhAKfOBgFOpAI1oJMnf4Dzz4w4C1AAabY4geSeNK5Q6G0EBfjLgMIgpxEU4MhAdrPfQfVN2DsBDqAQ9ebd0ZHLFt/wdwEcQLbR0/gx1RpfaTRY/oLo9T5SrTmBPhO6mKavAMUJ9PyaXT+AQshncZyiJ5A8A24gD6AGxIhcw/7s+s+ANq0jVUZm/vu5v9/W+yEGrM1Y6ghgSQ1ZQwPINC1r0YAlNWQNDSDTtKxFA5bUkDU0gEzTshYNWFJD1pTewA/wWX0xE5XaPwAAAABJRU5ErkJggg=='
]

{ #category : 'accessing - icons' }
CMCat class >> frame15 [
	"Private - Generated method"
	<script: 'self frame15 inspect'>
	^ self icons
		at: #frame15
		ifAbsentPut: [ Form fromBinaryStream: self frame15Contents base64Decoded asByteArray readStream ]
]

{ #category : 'private - contents' }
CMCat class >> frame15Contents [
	"Private - Method generated with the content of the file File @ /Users/zaitsev/Downloads/Basic Charakter Spritesheet/15_Basic Charakter Spritesheet.png"
	^ 'iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAABXAvmHAAAAAXNSR0IArs4c6QAAAV9JREFUaEPtlz8OAVEQxp9CpRWRLbiBG7iBOIELaFQalaioFBQusCcQN9Ar3EAkGxGtSkGGjLzsH4pvZtlkXvk2b978vm9mdrfkCr5KBc/fGcCvHTQHzAFQASshUED4uDkASwgGMAdAAeHj5gAsIRjAHMgSsNdd3PlZuB6oCaUSmJJfha03W7+3d1oQ4gCc/HV7eQJU2lVHALQ0IHIBYCs0nFADSOsNA0hRRdQBnjx+A/t3avSCKAAlG59AtEeJM5R0GYkCfHOAYSSnkShAwoGo/Kqg4Kb2ThAHYIigWU+0XHQ4ib8L1AC45s/HhhuPNo6AhsOdqzVnoneKBmPJ/UZmAHo2X0b/D5D2HURuaIxQEkXcAQKYTDtPM6h04ktyAqkAcBP7H288XqWTVwPI+kfQ2BcvIY0kP8U0gLwVj99nDpgDoAJWQqCA8HFzAJYQDGAOgALCx80BWEIwQOEdeAAXMIIxpvEXcwAAAABJRU5ErkJggg=='
]

{ #category : 'accessing' }
CMCat class >> icons [
	^ icons ifNil: [ icons := Dictionary new ]
]

{ #category : 'InspectorExtensions' }
CMCat class >> inspectionIcons [
	<inspectorPresentationOrder: 0 title: 'icons'>
	<script: 'self inspect'>
	^ SpTablePresenter new
		  addColumn: (SpImageTableColumn title: 'Icon' evaluated: #value);
		  addColumn: (SpStringTableColumn title: 'Name' evaluated: #key);
		  items:
			  ((self class selectorsInCategory: 'accessing - icons') sorted
				   collect: [ :each | each -> (self perform: each) ]);
		  yourself
]

{ #category : 'accessing - reset' }
CMCat class >> resetIcons [
	<script>
	^ icons := nil
]

{ #category : 'animations' }
CMCat class >> walkingDown [
	
	<script: 'self walkingDown inspect'>
	^ { 
		self frame00 .
		self frame01 .
		self frame02 .
		self frame03
	}
]

{ #category : 'animations' }
CMCat class >> walkingLeft [
	
	<script: 'self walkingLeft inspect'>
	^ { 
		self frame08 .
		self frame09 .
		self frame10 .
		self frame11
	}
]

{ #category : 'animations' }
CMCat class >> walkingRight [
	
	<script: 'self walkingRight inspect'>
	^ { 
		self frame12 .
		self frame13 .
		self frame14 .
		self frame15
	}
]

{ #category : 'animations' }
CMCat class >> walkingUp [
	
	<script: 'self walkingUp inspect'>
	^ { 
		self frame04 .
		self frame05 .
		self frame06 .
		self frame07
	}
]
