resources
endIconImage
	"Tools.UIMaskEditor new openOnClass: self andSelector: #endIconImage"
	
	<resource: #image>
	^CachedImage
		on:
			(Image
				extent: 26 @ 25
				depth: 6
				bitsPerPixel: 8
				palette:
					(MappedPalette
						withColors:
							(#(#(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(0 0 0)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(2826 2826 2826)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(5107 4946 4946)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(7934 7934 7934)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(4079 0 0)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(4079 4079 4079)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(1798 1798 1798)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(7677 0 0)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(6906 6906 6906)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(1284 835 835)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(1284 513 513)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(770 770 770)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(5878 5878 5878)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(3597 3597 3597)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(6392 0 0)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(2312 1798 1798)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(8191 0 0)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(4850 4850 4850)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(2569 2569 2569)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(7677 7677 7677)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(1798 513 513)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(1541 481 481)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(3854 3726 3726)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(2569 2087 2087)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(6906 0 0)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(6649 6649 6649)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(1541 1541 1541)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(1284 449 449)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(1284 610 610)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(3340 321 321)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(513 513 513)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(5621 5621 5621)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(3340 3340 3340)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(2312 513 513)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(5621 0 0)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(4593 4593 4593)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(1541 578 578)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(2312 2312 2312)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(7420 7420 7420)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(3854 3501 3501)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(4336 0 0)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(1284 1284 1284)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(6392 6392 6392)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(4336 4079 4079)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(7934 0 0)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(256 256 256)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(5364 5364 5364)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(3083 3083 3083)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(8191 8191 8191)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(1798 1284 1284)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(4336 4336 4336)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(3083 481 481)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(2055 2055 2055)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(3597 224 224)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(7163 7163 7163)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(770 417 417)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(2826 449 449)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(513 224 224)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(1027 1027 1027)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(5364 0 0)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(6135 6135 6135)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(3854 3854 3854)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(3854 353 353)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(5107 5107 5107)))
								collect:
									[:each | 
									(each at: 1) value
										perform: (each at: 2)
										withArguments: (each at: 3)]))
				usingBits:
					(ByteArray fromPackedString:
							'LC@0LC@0LC@0LC@0LC@0LC@0LC@0LC@0LC@@@C@0LC@0LC@0LC@SOBLEO30CLC@0LC@0LC@0@@@0LC@0LC@0LB8FG#PMAR<4KQH<LC@0LC@0L@@@LC@0LC@0BA(AJ#@0LC@0LC@_MAHSLC@0LC@@@C@0LC@0O@XYLC@0LC@0LC@0LC@_F!$0LC@0@@@0LC@0OCPSLC@0M 0EE0TLI#@0LCXFBC@0L@@@LC@0M!(SLC@0J0(!ABHDHQ0BLC@0B@XSLC@@@C@0LA(YLC@SLS8,DA@PDA@GL0<SLC@#CS@0@@@0LA<RLC@0C2HPDA@PDA@PDA@;C3@0@0XYL@@@LC@4OC@0@#LPDA@PDA@PDA@PDCLBLC@2OS@@@C@CG L0@3\GDA@PDA@PDA@PDA@GM0L0BB$0@@@0OCP0LA$UDA@PDA@PDA@PDA@PDATYLC@-@0@@LB8ALC@QGQ@PDA@PDA@PDA@PDA@]DS@0JP @@C@?K3@0E" PDA@PDA@PDA@PDA@PA@T0L@X*@@@0G1H0LB88DA@PDA@PDA@PDA@PDC .LC@:M @@LA$ZLC@HF1@PDA@PDA@PDA@PDA@[BC@CKS@@@C@0B2X0L@$XDA@PDA@PDA@PDA@XBS@0CBT0@@@0LB<?LC@*EA@PDA@PDA@PDA@PEB(0LB@QL@@@LC@6JPL0LB\5DA@PDA@PDA@,GR\0LBX:@3@@@C@0LC42LC@0I1PXDA@PDA@NIB,0LC@/O3@0@@@0LC@CD 00LC@*BS$!ABD9LP 0LC@QHC@0L@@@LC@0LAL4G3@0LC@SC@TLD3@0LC@QIPL0LC@@@C@0LC@0D1HMI#@0LC@0LC@0LCXRHC@0LC@0@@@0LC@0LC@0H2$ G0L0LC@&O0D:G3@0LC@0L@@@LC@0LC@0LC@SDQH-@@@@B2<.LC@0LC@0LC@@@@@a'))