resources
startIconImage
	"Tools.UIMaskEditor new openOnClass: self andSelector: #startIconImage"
	
	<resource: #image>
	^CachedImage
		on:
			(Image
				extent: 23 @ 24
				depth: 7
				bitsPerPixel: 8
				palette:
					(MappedPalette
						withColors:
							(#(#(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(0 0 0)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(7934 7934 7934)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(2698 2923 2698)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(160 3437 160)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(1798 2120 1798)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(289 3019 289)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(4079 4079 4079)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(160 3115 160)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(6906 6906 6906)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(289 417 289)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(224 385 224)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(1541 1830 1541)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(835 1124 835)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(0 4914 0)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(513 1606 513)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(0 4753 0)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(513 1445 513)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(513 1284 513)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(0 4593 0)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(5878 5878 5878)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(578 1156 578)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(642 867 642)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(3597 3758 3597)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(578 1316 578)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(4850 4850 4850)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(1060 1349 1060)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(995 1316 995)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(7677 7677 7677)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(2376 2633 2376)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(6649 6649 6649)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(0 4464 0)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(4304 4497 4304)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(0 4304 0)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(0 4143 0)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(0 3983 0)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(385 770 385)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(5621 5621 5621)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(449 642 449)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(481 2055 481)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(481 1734 481)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(7420 7420 7420)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(674 1027 674)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(3501 3693 3501)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(4946 5043 4946)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(6392 6392 6392)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(2601 2890 2601)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(0 3693 0)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(0 3533 0)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(256 2698 256)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(0 3212 0)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(0 3051 0)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(5364 5364 5364)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(3019 3212 3019)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(8191 8191 8191)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(128 192 128)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(610 1027 610)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(2826 3115 2826)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(481 1124 481)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(1991 2344 1991)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(7163 7163 7163)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(3372 3501 3372)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(417 610 417)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(963 1316 963)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(6135 6135 6135)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(128 2666 128)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(0 2923 0)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(770 1220 770)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(449 1863 449)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(321 2120 321)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(0 2762 0)) #(ColorValue 
								#scaledRed:scaledGreen:scaledBlue: #(0 2441 0)))
								collect:
									[:each | 
									(each at: 1) value
										perform: (each at: 2)
										withArguments: (each at: 3)]))
				usingBits:
					(ByteArray fromPackedString:
							'MST5MST5MST5MST5MST5MST5MST5MST@MST5MST5MST5N2PFA! ,MST5MST5MST@MST5MST5MQLYH2]FQ$PQIR(AMST5MST@MST5MSTAN@8"CP4MCP4MG#@>BCT5MST@MST5MQ4>AP4MCP4MCP4MCP4!EA<5MST@MST5JDH!CP4MCP4MCP4MCP4MC4L+MST@MST5N LMCP4MCP4MCP4MCP4MCQH7JCT@MST+I 4MCP4MCP4MCP4MCP4MCP4/ACT@MPD=D 4MCP4MCP4MCP4MCP4MCP4MC!L@MSMCCP4MCP4MCP4MCP4MCP4MCP4ML H@MSQACP4MCP4MCP4MCP4MCP4MCP4MHAT@MQ01CP4MCP4MCP4MCP4MCP4MCP4MCP@@MPP.CP4MCP4MCP4MCP4MCP4MCP4MCP@@MPH2CP4MCP4MCP4MCP4MCP4MCP4MC3X@MS1ECP4MCP4MCP4MCP4MCP4MCP4MHP0@MS<PCP4MCP4MCP4MCP4MCP4MCP4MPAX@MSTLHP4MCP4MCP4MCP4MCP4MCP4MNQ4@MST,DP4MCP4MCP4MCP4MCP4MCP40J#T@MST5J#@MCP4MCP4MCP4MCP4MCRD>@ST@MST5@Q(/CP4MCP4MCP4MCP4MG!\,MST@MST5MR DI!HMCP4MCP4MCP4GJS<5MST@MST5MST5J3\2D 4MCP4MK 8-F3T5MST@MST5MST5MR BBQ@PDA@JAAL5MST5MST@MST5MST5MST5MS<?O3<[MST5MST5MST@'))