resources
createEntityIconImage
	"Tools.UIMaskEditor new openOnClass: self andSelector: #createEntityIconImage"
	
	<resource: #image>
	^Image
		extent: 20 @ 18
		depth: 1
		bitsPerPixel: 1
		palette: MonoMappedPalette whiteBlack
		usingBits:
			#[0 0 0 0 0 0 0 0 0 0 0 0 0 240 0 0 0 144 0 0 0 144 0 0 0 144 0 0 15 159 0 0 8 1 0 0 8 1 0 0 15 159 0 0 0 144 0 0 0 144 0 0 0 144 0 0 0 240 0 0 0 0 0 0 0 0 0 0 0 0 0 0]