Class {
	#name : 'CMEnglishTranslator',
	#superclass : 'CMAbstractTranslator',
	#category : 'Cormas-UI-Translator',
	#package : 'Cormas-UI-Translator'
}

{ #category : 'translations' }
CMEnglishTranslator >> tCharts [

	^ 'Charts'
]

{ #category : 'translations' }
CMEnglishTranslator >> tClass [

	^ 'Class'
]

{ #category : 'translations' }
CMEnglishTranslator >> tData [

	^ 'Data'
]

{ #category : 'translations' }
CMEnglishTranslator >> tDisplayEveryLabel [

	^ 'Display every'
]

{ #category : 'translations' }
CMEnglishTranslator >> tFinalStepLabel [

	^ 'Final step'
]

{ #category : 'translations' }
CMEnglishTranslator >> tInspector [

	^ 'Inspector'
]

{ #category : 'translations' }
CMEnglishTranslator >> tParameter [

	^ 'Parameter'
]

{ #category : 'translations' }
CMEnglishTranslator >> tParameters [

	^ 'Parameters'
]

{ #category : 'translations' }
CMEnglishTranslator >> tProgressBarLabel [

	^ 'Progress'
]

{ #category : 'translations' }
CMEnglishTranslator >> tRunButtonHelp [

	^ 'Run the simulation to the end'
]

{ #category : 'translations' }
CMEnglishTranslator >> tRunButtonLabel [ 

	^ 'Run'
]

{ #category : 'translations' }
CMEnglishTranslator >> tSpace [

	^ 'Space'
]

{ #category : 'translations' }
CMEnglishTranslator >> tSpeed10xFaster [

	^ '10x faster'
]

{ #category : 'translations' }
CMEnglishTranslator >> tSpeed10xSlower [

	^ '10x slower'
]

{ #category : 'translations' }
CMEnglishTranslator >> tSpeed2xFaster [

	^ '2x faster'
]

{ #category : 'translations' }
CMEnglishTranslator >> tSpeed2xSlower [

	^ '2x slower'
]

{ #category : 'translations' }
CMEnglishTranslator >> tSpeed5xFaster [

	^ '5x faster'
]

{ #category : 'translations' }
CMEnglishTranslator >> tSpeed5xSlower [ 

	^ '5x slower'
]

{ #category : 'translations' }
CMEnglishTranslator >> tSpeedHelp [

	^ 'Speed of simulation'
]

{ #category : 'translations' }
CMEnglishTranslator >> tSpeedLabel [

	^ 'Speed'
]

{ #category : 'translations' }
CMEnglishTranslator >> tSpeedNormal [

	^ 'normal'
]

{ #category : 'translations' }
CMEnglishTranslator >> tStepButtonHelp [

	^ 'Run the simulation just one step forward'
]

{ #category : 'translations' }
CMEnglishTranslator >> tStepButtonLabel [ 

	^ 'Step'
]

{ #category : 'translations' }
CMEnglishTranslator >> tValue [

	^ 'Value'
]
