Class {
	#name : 'CMEnglishTranslator',
	#superclass : 'CMAbstractTranslator',
	#category : 'Cormas-UI-Translator',
	#package : 'Cormas-UI-Translator'
}

{ #category : 'translations' }
CMEnglishTranslator >> tAdd [

	^ 'Add'
]

{ #category : 'translations' }
CMEnglishTranslator >> tAddMeasurementHelp [

	^ 'Add new probe measurement'
]

{ #category : 'translations' }
CMEnglishTranslator >> tAverageValue [

	^ 'Average value'
]

{ #category : 'translations' }
CMEnglishTranslator >> tCharts [

	^ 'Charts'
]

{ #category : 'translations' }
CMEnglishTranslator >> tClass [

	^ 'Class'
]

{ #category : 'translations' }
CMEnglishTranslator >> tControlMethod [

	^ 'Control method'
]

{ #category : 'translations' }
CMEnglishTranslator >> tData [

	^ 'Data'
]

{ #category : 'translations' }
CMEnglishTranslator >> tDisplayEveryLabel [

	^ 'Display every'
]

{ #category : 'translations' }
CMEnglishTranslator >> tFinalStep [

	^ 'Final step'
]

{ #category : 'translations' }
CMEnglishTranslator >> tFinalValue [

	^ 'Final value'
]

{ #category : 'translations' }
CMEnglishTranslator >> tFixRandomSeed [

	^ 'Fix random seed:'
]

{ #category : 'translations' }
CMEnglishTranslator >> tInitMethod [

	^ 'Init method'
]

{ #category : 'translations' }
CMEnglishTranslator >> tInspector [

	^ 'Inspector'
]

{ #category : 'translations' }
CMEnglishTranslator >> tMaximumValue [

	^ 'Maximum value'
]

{ #category : 'translations' }
CMEnglishTranslator >> tMeasure [

	^ 'Measure'
]

{ #category : 'translations' }
CMEnglishTranslator >> tMeasureOf [

	^ 'of'
]

{ #category : 'translations' }
CMEnglishTranslator >> tMinimumValue [

	^ 'Minimum value'
]

{ #category : 'translations' }
CMEnglishTranslator >> tNumberOfRepetitions [

	^ 'Number of repetitions'
]

{ #category : 'translations' }
CMEnglishTranslator >> tParameter [

	^ 'Parameter'
]

{ #category : 'translations' }
CMEnglishTranslator >> tParameters [

	^ 'Parameters'
]

{ #category : 'translations' }
CMEnglishTranslator >> tProbesToBeMeasured [

	^ 'Probes to be measured'
]

{ #category : 'translations' }
CMEnglishTranslator >> tProgressBarLabel [

	^ 'Progress'
]

{ #category : 'translations' }
CMEnglishTranslator >> tReleaseRandomSeedAfterInitialization [

	^ 'Release random seed after initialization'
]

{ #category : 'translations' }
CMEnglishTranslator >> tRun [ 

	^ 'Run'
]

{ #category : 'translations' }
CMEnglishTranslator >> tRunButtonHelp [

	^ 'Run the simulation to the end'
]

{ #category : 'translations' }
CMEnglishTranslator >> tSensitivityAnalysis [

	^ 'Sensitivity Analysis'
]

{ #category : 'translations' }
CMEnglishTranslator >> tSpace [

	^ 'Space'
]

{ #category : 'translations' }
CMEnglishTranslator >> tSpeed10xFaster [

	^ '10x faster'
]

{ #category : 'translations' }
CMEnglishTranslator >> tSpeed10xSlower [

	^ '10x slower'
]

{ #category : 'translations' }
CMEnglishTranslator >> tSpeed2xFaster [

	^ '2x faster'
]

{ #category : 'translations' }
CMEnglishTranslator >> tSpeed2xSlower [

	^ '2x slower'
]

{ #category : 'translations' }
CMEnglishTranslator >> tSpeed5xFaster [

	^ '5x faster'
]

{ #category : 'translations' }
CMEnglishTranslator >> tSpeed5xSlower [ 

	^ '5x slower'
]

{ #category : 'translations' }
CMEnglishTranslator >> tSpeedHelp [

	^ 'Speed of simulation'
]

{ #category : 'translations' }
CMEnglishTranslator >> tSpeedLabel [

	^ 'Speed'
]

{ #category : 'translations' }
CMEnglishTranslator >> tSpeedNormal [

	^ 'normal'
]

{ #category : 'translations' }
CMEnglishTranslator >> tStepButtonHelp [

	^ 'Run the simulation just one step forward'
]

{ #category : 'translations' }
CMEnglishTranslator >> tStepButtonLabel [ 

	^ 'Step'
]

{ #category : 'translations' }
CMEnglishTranslator >> tValue [

	^ 'Value'
]
