Class {
	#name : 'CMUkrainianTranslator',
	#superclass : 'CMAbstractTranslator',
	#category : 'Cormas-UI-Translator',
	#package : 'Cormas-UI-Translator'
}

{ #category : 'translations' }
CMUkrainianTranslator >> tAdd [

	^ 'Додати'
]

{ #category : 'translations' }
CMUkrainianTranslator >> tAddMeasurementHelp [

	^ 'Додати нове вимірювання'
]

{ #category : 'translations' }
CMUkrainianTranslator >> tAverageValue [

	^ 'Середнє значення'
]

{ #category : 'translations' }
CMUkrainianTranslator >> tCharts [

	^ 'Графіки'
]

{ #category : 'translations' }
CMUkrainianTranslator >> tClass [

	^ 'Клас'
]

{ #category : 'translations' }
CMUkrainianTranslator >> tControlMethod [

	^ 'Метод контролю'
]

{ #category : 'translations' }
CMUkrainianTranslator >> tData [

	^ 'Дані'
]

{ #category : 'translations' }
CMUkrainianTranslator >> tDisplayEveryLabel [

	^ 'Показувати кожні'
]

{ #category : 'translations' }
CMUkrainianTranslator >> tFinalStep [

	^ 'Фінальний крок'
]

{ #category : 'translations' }
CMUkrainianTranslator >> tFinalValue [

	^ 'Фінальне значення'
]

{ #category : 'translations' }
CMUkrainianTranslator >> tFixRandomSeed [

	^ 'Випадкове початкове значення:'
]

{ #category : 'translations' }
CMUkrainianTranslator >> tInitMethod [

	^ 'Метод ініціалізації'
]

{ #category : 'translations' }
CMUkrainianTranslator >> tInspector [

	^ 'Інспектор'
]

{ #category : 'translations' }
CMUkrainianTranslator >> tMaximumValue [

	^ 'Максимальне значення'
]

{ #category : 'translations' }
CMUkrainianTranslator >> tMeasure [

	^ 'Виміряти'
]

{ #category : 'translations' }
CMUkrainianTranslator >> tMeasureOf [

	^ 'від'
]

{ #category : 'translations' }
CMUkrainianTranslator >> tMeasurementType [

	^ 'Тип вимірювання'
]

{ #category : 'translations' }
CMUkrainianTranslator >> tMinimumValue [

	^ 'Мінімальне значення'
]

{ #category : 'translations' }
CMUkrainianTranslator >> tMonteCarlo [

	^ 'Монте Карло'
]

{ #category : 'translations' }
CMUkrainianTranslator >> tNumberOfRepetitions [

	^ 'Кількість повторів'
]

{ #category : 'translations' }
CMUkrainianTranslator >> tParameter [

	^ 'Параметр'
]

{ #category : 'translations' }
CMUkrainianTranslator >> tParameters [

	^ 'Параметри'
]

{ #category : 'translations' }
CMUkrainianTranslator >> tPredefinedList [

	^ 'Список'
]

{ #category : 'translations' }
CMUkrainianTranslator >> tProbe [

	^ 'Проба'
]

{ #category : 'translations' }
CMUkrainianTranslator >> tProbesToBeMeasured [

	^ 'Проби які потрібно виміряти'
]

{ #category : 'translations' }
CMUkrainianTranslator >> tProgressBarLabel [

	^ 'Прогрес'
]

{ #category : 'translations' }
CMUkrainianTranslator >> tRange [

	^ 'Діапазон'
]

{ #category : 'translations' }
CMUkrainianTranslator >> tReleaseRandomSeedAfterInitialization [

	^ 'Скинути випадкове значення після ініціалізації'
]

{ #category : 'translations' }
CMUkrainianTranslator >> tRun [

	^ 'Запустити'
]

{ #category : 'translations' }
CMUkrainianTranslator >> tRunButtonHelp [

	^ 'Грати симуляцію до самого кінця'
]

{ #category : 'translations' }
CMUkrainianTranslator >> tSensitivityAnalysis [

	^ 'Аналіз Сенситивності'
]

{ #category : 'translations' }
CMUkrainianTranslator >> tSpace [

	^ 'Простір'
]

{ #category : 'translations' }
CMUkrainianTranslator >> tSpeed10xFaster [

	^ '10x швидша'
]

{ #category : 'translations' }
CMUkrainianTranslator >> tSpeed10xSlower [

	^ '10x повільніша'
]

{ #category : 'translations' }
CMUkrainianTranslator >> tSpeed2xFaster [

	^ '2x швидша'
]

{ #category : 'translations' }
CMUkrainianTranslator >> tSpeed2xSlower [

	^ '2x повільніша'
]

{ #category : 'translations' }
CMUkrainianTranslator >> tSpeed5xFaster [

	^ '5x швидша'
]

{ #category : 'translations' }
CMUkrainianTranslator >> tSpeed5xSlower [

	^ '5x повільніша'
]

{ #category : 'translations' }
CMUkrainianTranslator >> tSpeedHelp [

	^ 'Швидкість симуляції'
]

{ #category : 'translations' }
CMUkrainianTranslator >> tSpeedLabel [

	^ 'Швидкість'
]

{ #category : 'translations' }
CMUkrainianTranslator >> tSpeedNormal [

	^ 'нормальна'
]

{ #category : 'translations' }
CMUkrainianTranslator >> tStepButtonHelp [

	^ 'Пройти один крок симуляції'
]

{ #category : 'translations' }
CMUkrainianTranslator >> tStepButtonLabel [

	^ 'Крок'
]

{ #category : 'translations' }
CMUkrainianTranslator >> tStrategy [

	^ 'Стратегія'
]

{ #category : 'translations' }
CMUkrainianTranslator >> tValue [

	^ 'Значення'
]
