Extension { #name : 'Object' }

{ #category : '*Cormas-Core' }
Object class >> isCormasAgentClass [

	^ false
]

{ #category : '*Cormas-Core' }
Object class >> isCormasCellClass [

	^ false
]

{ #category : '*Cormas-Core' }
Object >> isCormasEntity [

	^ false
]

{ #category : '*Cormas-Core' }
Object class >> isCormasEntityClass [

	^ false
]

{ #category : '*Cormas-Core' }
Object class >> isCormasModelClass [

	^ false
]
