description
versionComments
	
	^' 

 --------------------- ECEC_tutorial.pcl --------------------- Date: 2012.8.21 - 8:58:18
3 initializaton methods
 *** Developer: L√©on Iladubobo ***

 --------------------- ECEC_tutorial.pcl --------------------- Date: 2012.8.21 - 8:58:18
First full version
 *** Developer: L√©on Iladubobo ***

 --------------------- ECEC_tutorial.pcl --------------------- Date: 2012.8.21 - 17:22:10
First version with no bug !
 *** Developer: L√©on Iladubobo ***

 --------------------- ECEC_tutorial.pcl --------------------- Date: 2012.8.23 - 12:53:54
Probe curves with predefined colors
 *** Developer: L√©on Iladubobo ***

 --------------------- ECEC_tutorial.pcl --------------------- Date: 2012.8.23 - 12:53:54
with activity diagram
 *** Developer: L√©on Iladubobo ***

 --------------------- ECEC_tutorial.pcl --------------------- Date: 2012.8.23 - 12:53:54
Modified Activity diagram for the Restrained foragers
 *** Developer: L√©on Iladubobo ***'