ADvance
ad2diagram_Entity_ClassDiagram
	
	^#(AD2DiagramSpec 
		#name: 'Entity_ClassDiagram' 
		#creationDateSeconds: 3435471503 
		#modificationDateSeconds: 3435471539 
		#author: #(AD2Identity 
			#nickName: 'Pierre' 
			#name: 'Bommel' 
			#company: 'CIRAD - Green') 
		#state: #(AD2DiagramState 
			#bits: 7 
			#zoom: '100%' 
			#translation: #(Point -60 -50) 
			#scriptDepth: 3 
			#associationDepth: 2) 
		#filter: #(AD2StructureFilter 
			#bits: 77 
			#filteredInstProtocols: #('access-*' 'accessing-*' 'aspects' 'backward*' 'boss*' 'chang*' 'encode-decod*' 'exampl*' 'fileI*' 'fileO*' 'interface*' 'menu*' 'primitiv*' 'resources') 
			#filteredInstMethods: #('displayOn:*' 'displayString' 'init*' 'printOn:' 'printString' 'releas*' 'storeOn:' 'storeString' 'update:*') 
			#filteredClassProtocols: #('*declarations' '*specs' 'access-*' 'accessing-*' 'ADvance*' 'backward*' 'constants' 'documentation' 'exampl*' 'fileIn/Out' 'info' 'resources' 'signal*') 
			#filteredClassMethods: #('initialize' 'new') 
			#filteredInstVars: #() 
			#filteredClassInstVars: #() 
			#filteredSharedVars: #()) 
		#classes: #(#(AgentLocation 1135 434 1) #(#CMGroupComm 1799 599 1) #(#CMSpatialEntityAggregate 142 725 1) #(#CMObjectLocation 2045 434 1) #(#CMSpatialEntityNotConnex 440 725 1) #(#CMSpatialEntity 512 323 1) #(AgentComm 1799 434 1) #(#CMSpatialEntityElement 733 578 1) #(Group 1541 434 1) #(Entity 1278 50 1) #(Agent 1467 323 1) #(#CMGroupCommLocation 1268 728 1) #(#CMSpatialEntitySet 291 578 1) #(PassiveObject 2045 323 1) #(#CMAgentCommLocation 1268 563 1) #(#CMSpatialEntityCell 734 689 1) #(#CMGroupLocation 1003 563 1)))