pov symbols
VectorialPOV_Restrained
	"Returns an array containing the settings of a Situated entity vectorial pov symbol in the following order:
(color red) (color green) (color blue) (lineColor red) (lineColor green) (lineColor blue) lineWidth sizeratio position (array of outline vertices)"
	
	^#(0.0 0.329996 1.0 0.0 0.0 0.0 1 0.7 #center #(-7.395 #@- 9.6963 24.99 #@- 13.537 16.32 #@ 24.8704 4.08 #@ 4.72222 -9.69 #@ 24.2407 -10.71 #@ 10.3889 -14.28 #@ 2.83333 -26.01 #@- 4.09259 -25.5 #@- 9.12963 -15.81 #@- 13.537 -13.26 #@- 26.1296 -13.26 #@- 14.1667 -7.395 #@- 9.6963))